// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: handlerrpctest/test.proto

package handlerrpctest

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	handlerrpc "github.com/unstablebuild/rune-go-sdk/handler/handlerrpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRequest) Reset() {
	*x = TestRequest{}
	mi := &file_handlerrpctest_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRequest) ProtoMessage() {}

func (x *TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_handlerrpctest_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRequest.ProtoReflect.Descriptor instead.
func (*TestRequest) Descriptor() ([]byte, []int) {
	return file_handlerrpctest_test_proto_rawDescGZIP(), []int{0}
}

type TestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	mi := &file_handlerrpctest_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_handlerrpctest_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_handlerrpctest_test_proto_rawDescGZIP(), []int{1}
}

type TestMessage struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Type          handlerrpc.MessageType               `protobuf:"varint,1,opt,name=type,proto3,enum=handler.MessageType" json:"type,omitempty"`
	Draw          *handlerrpc.DrawStreamResponse       `protobuf:"bytes,2,opt,name=draw,proto3" json:"draw,omitempty"`
	Handle        *handlerrpc.HandleStreamResponse     `protobuf:"bytes,3,opt,name=handle,proto3" json:"handle,omitempty"`
	Man           any                                  `protobuf:"bytes,4,opt,name=man,proto3" json:"man,omitempty"`
	Close         *handlerrpc.CloseStreamResponse      `protobuf:"bytes,5,opt,name=close,proto3" json:"close,omitempty"`
	Cursor        *handlerrpc.CursorStreamResponse     `protobuf:"bytes,6,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Selection     *handlerrpc.SelectionStreamResponse  `protobuf:"bytes,7,opt,name=selection,proto3" json:"selection,omitempty"`
	Dimensions    *handlerrpc.DimensionsStreamResponse `protobuf:"bytes,8,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Request       *TestRequest                         `protobuf:"bytes,10,opt,name=request,proto3" json:"request,omitempty"`
	Response      *TestResponse                        `protobuf:"bytes,11,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMessage) Reset() {
	*x = TestMessage{}
	mi := &file_handlerrpctest_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage) ProtoMessage() {}

func (x *TestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_handlerrpctest_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage.ProtoReflect.Descriptor instead.
func (*TestMessage) Descriptor() ([]byte, []int) {
	return file_handlerrpctest_test_proto_rawDescGZIP(), []int{2}
}

func (x *TestMessage) GetType() handlerrpc.MessageType {
	if x != nil {
		return x.Type
	}
	return handlerrpc.MessageType(0)
}

func (x *TestMessage) GetDraw() *handlerrpc.DrawStreamResponse {
	if x != nil {
		return x.Draw
	}
	return nil
}

func (x *TestMessage) GetHandle() *handlerrpc.HandleStreamResponse {
	if x != nil {
		return x.Handle
	}
	return nil
}

func (x *TestMessage) GetClose() *handlerrpc.CloseStreamResponse {
	if x != nil {
		return x.Close
	}
	return nil
}

func (x *TestMessage) GetCursor() *handlerrpc.CursorStreamResponse {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *TestMessage) GetSelection() *handlerrpc.SelectionStreamResponse {
	if x != nil {
		return x.Selection
	}
	return nil
}

func (x *TestMessage) GetDimensions() *handlerrpc.DimensionsStreamResponse {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *TestMessage) GetRequest() *TestRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *TestMessage) GetResponse() *TestResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_handlerrpctest_test_proto protoreflect.FileDescriptor

const file_handlerrpctest_test_proto_rawDesc = "" +
	"\n" +
	"\x19handlerrpctest/test.proto\x12\x04test\x1a handler/handlerrpc/handler.proto\"\r\n" +
	"\vTestRequest\"\x0e\n" +
	"\fTestResponse\"\x98\x04\n" +
	"\vTestMessage\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.handler.MessageTypeR\x04type\x12/\n" +
	"\x04draw\x18\x02 \x01(\v2\x1b.handler.DrawStreamResponseR\x04draw\x125\n" +
	"\x06handle\x18\x03 \x01(\v2\x1d.handler.HandleStreamResponseR\x06handle\x12,\n" +
	"\x03man\x18\x04 \x01(\v2\x1a.handler.ManStreamResponseR\x03man\x122\n" +
	"\x05close\x18\x05 \x01(\v2\x1c.handler.CloseStreamResponseR\x05close\x125\n" +
	"\x06cursor\x18\x06 \x01(\v2\x1d.handler.CursorStreamResponseR\x06cursor\x12>\n" +
	"\tselection\x18\a \x01(\v2 .handler.SelectionStreamResponseR\tselection\x12A\n" +
	"\n" +
	"dimensions\x18\b \x01(\v2!.handler.DimensionsStreamResponseR\n" +
	"dimensions\x12+\n" +
	"\arequest\x18\n" +
	" \x01(\v2\x11.test.TestRequestR\arequest\x12.\n" +
	"\bresponse\x18\v \x01(\v2\x12.test.TestResponseR\bresponse2L\n" +
	"\vTestService\x12=\n" +
	"\n" +
	"TestStream\x12\x11.test.TestMessage\x1a\x16.handler.ServerMessage\"\x00(\x010\x01B\x11Z\x0f/handlerrpctestb\x06proto3"

var (
	file_handlerrpctest_test_proto_rawDescOnce sync.Once
	file_handlerrpctest_test_proto_rawDescData []byte
)

func file_handlerrpctest_test_proto_rawDescGZIP() []byte {
	file_handlerrpctest_test_proto_rawDescOnce.Do(func() {
		file_handlerrpctest_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_handlerrpctest_test_proto_rawDesc), len(file_handlerrpctest_test_proto_rawDesc)))
	})
	return file_handlerrpctest_test_proto_rawDescData
}

var file_handlerrpctest_test_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_handlerrpctest_test_proto_goTypes = []any{
	(*TestRequest)(nil),                         // 0: test.TestRequest
	(*TestResponse)(nil),                        // 1: test.TestResponse
	(*TestMessage)(nil),                         // 2: test.TestMessage
	(handlerrpc.MessageType)(0),                 // 3: handler.MessageType
	(*handlerrpc.DrawStreamResponse)(nil),       // 4: handler.DrawStreamResponse
	(*handlerrpc.HandleStreamResponse)(nil),     // 5: handler.HandleStreamResponse
	nil,                                         // 6: handler.ManStreamResponse
	(*handlerrpc.CloseStreamResponse)(nil),      // 7: handler.CloseStreamResponse
	(*handlerrpc.CursorStreamResponse)(nil),     // 8: handler.CursorStreamResponse
	(*handlerrpc.SelectionStreamResponse)(nil),  // 9: handler.SelectionStreamResponse
	(*handlerrpc.DimensionsStreamResponse)(nil), // 10: handler.DimensionsStreamResponse
	(*handlerrpc.ServerMessage)(nil),            // 11: handler.ServerMessage
}
var file_handlerrpctest_test_proto_depIdxs = []int32{
	3,  // 0: test.TestMessage.type:type_name -> handler.MessageType
	4,  // 1: test.TestMessage.draw:type_name -> handler.DrawStreamResponse
	5,  // 2: test.TestMessage.handle:type_name -> handler.HandleStreamResponse
	6,  // 3: test.TestMessage.man:type_name -> handler.ManStreamResponse
	7,  // 4: test.TestMessage.close:type_name -> handler.CloseStreamResponse
	8,  // 5: test.TestMessage.cursor:type_name -> handler.CursorStreamResponse
	9,  // 6: test.TestMessage.selection:type_name -> handler.SelectionStreamResponse
	10, // 7: test.TestMessage.dimensions:type_name -> handler.DimensionsStreamResponse
	0,  // 8: test.TestMessage.request:type_name -> test.TestRequest
	1,  // 9: test.TestMessage.response:type_name -> test.TestResponse
	2,  // 10: test.TestService.TestStream:input_type -> test.TestMessage
	11, // 11: test.TestService.TestStream:output_type -> handler.ServerMessage
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_handlerrpctest_test_proto_init() }
func file_handlerrpctest_test_proto_init() {
	if File_handlerrpctest_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_handlerrpctest_test_proto_rawDesc), len(file_handlerrpctest_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_handlerrpctest_test_proto_goTypes,
		DependencyIndexes: file_handlerrpctest_test_proto_depIdxs,
		MessageInfos:      file_handlerrpctest_test_proto_msgTypes,
	}.Build()
	File_handlerrpctest_test_proto = out.File
	file_handlerrpctest_test_proto_goTypes = nil
	file_handlerrpctest_test_proto_depIdxs = nil
}
