syntax = "proto3";

option go_package = "unstable.build/go-tui/handler/rpc";

import "term/rpc/term.proto";

package handler;

message DrawRequest {
	int32 width = 1;
	int32 height = 2;
}

message DrawResponse {
	message Cursor {
		term.Coordinates position = 1;
		bool show = 2;
		int32 style = 3;
	}

	repeated term.CellRow rows = 1;
	Cursor cursor = 2;
}

message HandleRequest {
	term.Event event = 1;

	DrawRequest draw = 2;
}

message HandleResponse {
	bool handled = 1;
	bool quit = 2;

	DrawResponse draw = 3;
}

message ManRequest {}

message ManResponse {
	term.Manual man = 1;
}

message CloseRequest {
}

message CloseResponse {}

service Handler {
	rpc Handle(HandleRequest) returns (HandleResponse);
	rpc Man(ManRequest) returns (ManResponse);
	rpc Close(CloseRequest) returns (CloseResponse);
}
