// Code generated by MockGen. DO NOT EDIT.
// Source: browser.go

// Package browser is a generated GoMock package.
package browser

import (
	context "context"
	reflect "reflect"

	document "github.com/ernestrc/blue/datastore/document"
	go_tui "github.com/ernestrc/go-tui"
	term "github.com/ernestrc/go-tui/term"
	gomock "github.com/golang/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// Cursor mocks base method.
func (m *MockHandler) Cursor() (term.Coordinates, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cursor")
	ret0, _ := ret[0].(term.Coordinates)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Cursor indicates an expected call of Cursor.
func (mr *MockHandlerMockRecorder) Cursor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cursor", reflect.TypeOf((*MockHandler)(nil).Cursor))
}

// Draw mocks base method.
func (m *MockHandler) Draw(arg0 term.Writer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Draw", arg0)
}

// Draw indicates an expected call of Draw.
func (mr *MockHandlerMockRecorder) Draw(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Draw", reflect.TypeOf((*MockHandler)(nil).Draw), arg0)
}

// Handle mocks base method.
func (m *MockHandler) Handle(arg0 term.Event) (bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockHandlerMockRecorder) Handle(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockHandler)(nil).Handle), arg0)
}

// Man mocks base method.
func (m *MockHandler) Man() go_tui.Manual {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Man")
	ret0, _ := ret[0].(go_tui.Manual)
	return ret0
}

// Man indicates an expected call of Man.
func (mr *MockHandlerMockRecorder) Man() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Man", reflect.TypeOf((*MockHandler)(nil).Man))
}

// OnUnmount mocks base method.
func (m *MockHandler) OnUnmount() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnUnmount")
	ret0, _ := ret[0].(error)
	return ret0
}

// OnUnmount indicates an expected call of OnUnmount.
func (mr *MockHandlerMockRecorder) OnUnmount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnUnmount", reflect.TypeOf((*MockHandler)(nil).OnUnmount))
}

// Resize mocks base method.
func (m *MockHandler) Resize(width, height int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Resize", width, height)
}

// Resize indicates an expected call of Resize.
func (mr *MockHandlerMockRecorder) Resize(width, height interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resize", reflect.TypeOf((*MockHandler)(nil).Resize), width, height)
}

// MockWindow is a mock of Window interface.
type MockWindow struct {
	ctrl     *gomock.Controller
	recorder *MockWindowMockRecorder
}

// MockWindowMockRecorder is the mock recorder for MockWindow.
type MockWindowMockRecorder struct {
	mock *MockWindow
}

// NewMockWindow creates a new mock instance.
func NewMockWindow(ctrl *gomock.Controller) *MockWindow {
	mock := &MockWindow{ctrl: ctrl}
	mock.recorder = &MockWindowMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWindow) EXPECT() *MockWindowMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockWindow) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockWindowMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWindow)(nil).Close))
}

// Content mocks base method.
func (m *MockWindow) Content() (Handler, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Content")
	ret0, _ := ret[0].(Handler)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Content indicates an expected call of Content.
func (mr *MockWindowMockRecorder) Content() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Content", reflect.TypeOf((*MockWindow)(nil).Content))
}

// SetContent mocks base method.
func (m *MockWindow) SetContent(arg0 Handler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetContent", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetContent indicates an expected call of SetContent.
func (mr *MockWindowMockRecorder) SetContent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetContent", reflect.TypeOf((*MockWindow)(nil).SetContent), arg0)
}

// id mocks base method.
func (m *MockWindow) id() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "id")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// id indicates an expected call of id.
func (mr *MockWindowMockRecorder) id() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "id", reflect.TypeOf((*MockWindow)(nil).id))
}

// onWindowClosed mocks base method.
func (m *MockWindow) onWindowClosed(fn func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "onWindowClosed", fn)
}

// onWindowClosed indicates an expected call of onWindowClosed.
func (mr *MockWindowMockRecorder) onWindowClosed(fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "onWindowClosed", reflect.TypeOf((*MockWindow)(nil).onWindowClosed), fn)
}

// MockWindowManager is a mock of WindowManager interface.
type MockWindowManager struct {
	ctrl     *gomock.Controller
	recorder *MockWindowManagerMockRecorder
}

// MockWindowManagerMockRecorder is the mock recorder for MockWindowManager.
type MockWindowManagerMockRecorder struct {
	mock *MockWindowManager
}

// NewMockWindowManager creates a new mock instance.
func NewMockWindowManager(ctrl *gomock.Controller) *MockWindowManager {
	mock := &MockWindowManager{ctrl: ctrl}
	mock.recorder = &MockWindowManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWindowManager) EXPECT() *MockWindowManagerMockRecorder {
	return m.recorder
}

// FloatingWindow mocks base method.
func (m *MockWindowManager) FloatingWindow(h Handler, at term.Coordinates, width, height int) (Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FloatingWindow", h, at, width, height)
	ret0, _ := ret[0].(Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FloatingWindow indicates an expected call of FloatingWindow.
func (mr *MockWindowManagerMockRecorder) FloatingWindow(h, at, width, height interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FloatingWindow", reflect.TypeOf((*MockWindowManager)(nil).FloatingWindow), h, at, width, height)
}

// Focus mocks base method.
func (m *MockWindowManager) Focus() (Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Focus")
	ret0, _ := ret[0].(Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Focus indicates an expected call of Focus.
func (mr *MockWindowManagerMockRecorder) Focus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Focus", reflect.TypeOf((*MockWindowManager)(nil).Focus))
}

// SplitHorizontalAbove mocks base method.
func (m *MockWindowManager) SplitHorizontalAbove(arg0 Handler) (Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SplitHorizontalAbove", arg0)
	ret0, _ := ret[0].(Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SplitHorizontalAbove indicates an expected call of SplitHorizontalAbove.
func (mr *MockWindowManagerMockRecorder) SplitHorizontalAbove(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SplitHorizontalAbove", reflect.TypeOf((*MockWindowManager)(nil).SplitHorizontalAbove), arg0)
}

// SplitHorizontalBelow mocks base method.
func (m *MockWindowManager) SplitHorizontalBelow(arg0 Handler) (Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SplitHorizontalBelow", arg0)
	ret0, _ := ret[0].(Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SplitHorizontalBelow indicates an expected call of SplitHorizontalBelow.
func (mr *MockWindowManagerMockRecorder) SplitHorizontalBelow(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SplitHorizontalBelow", reflect.TypeOf((*MockWindowManager)(nil).SplitHorizontalBelow), arg0)
}

// SplitVerticalLeft mocks base method.
func (m *MockWindowManager) SplitVerticalLeft(arg0 Handler) (Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SplitVerticalLeft", arg0)
	ret0, _ := ret[0].(Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SplitVerticalLeft indicates an expected call of SplitVerticalLeft.
func (mr *MockWindowManagerMockRecorder) SplitVerticalLeft(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SplitVerticalLeft", reflect.TypeOf((*MockWindowManager)(nil).SplitVerticalLeft), arg0)
}

// SplitVerticalRight mocks base method.
func (m *MockWindowManager) SplitVerticalRight(arg0 Handler) (Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SplitVerticalRight", arg0)
	ret0, _ := ret[0].(Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SplitVerticalRight indicates an expected call of SplitVerticalRight.
func (mr *MockWindowManagerMockRecorder) SplitVerticalRight(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SplitVerticalRight", reflect.TypeOf((*MockWindowManager)(nil).SplitVerticalRight), arg0)
}

// MockEventHandler is a mock of EventHandler interface.
type MockEventHandler struct {
	ctrl     *gomock.Controller
	recorder *MockEventHandlerMockRecorder
}

// MockEventHandlerMockRecorder is the mock recorder for MockEventHandler.
type MockEventHandlerMockRecorder struct {
	mock *MockEventHandler
}

// NewMockEventHandler creates a new mock instance.
func NewMockEventHandler(ctrl *gomock.Controller) *MockEventHandler {
	mock := &MockEventHandler{ctrl: ctrl}
	mock.recorder = &MockEventHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventHandler) EXPECT() *MockEventHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockEventHandler) Handle(arg0 term.Event) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockEventHandlerMockRecorder) Handle(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockEventHandler)(nil).Handle), arg0)
}

// MockEventSubscriber is a mock of EventSubscriber interface.
type MockEventSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockEventSubscriberMockRecorder
}

// MockEventSubscriberMockRecorder is the mock recorder for MockEventSubscriber.
type MockEventSubscriberMockRecorder struct {
	mock *MockEventSubscriber
}

// NewMockEventSubscriber creates a new mock instance.
func NewMockEventSubscriber(ctrl *gomock.Controller) *MockEventSubscriber {
	mock := &MockEventSubscriber{ctrl: ctrl}
	mock.recorder = &MockEventSubscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventSubscriber) EXPECT() *MockEventSubscriberMockRecorder {
	return m.recorder
}

// Subscribe mocks base method.
func (m *MockEventSubscriber) Subscribe(arg0 term.Event, arg1 EventHandler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockEventSubscriberMockRecorder) Subscribe(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockEventSubscriber)(nil).Subscribe), arg0, arg1)
}

// MockKeyMapper is a mock of KeyMapper interface.
type MockKeyMapper struct {
	ctrl     *gomock.Controller
	recorder *MockKeyMapperMockRecorder
}

// MockKeyMapperMockRecorder is the mock recorder for MockKeyMapper.
type MockKeyMapperMockRecorder struct {
	mock *MockKeyMapper
}

// NewMockKeyMapper creates a new mock instance.
func NewMockKeyMapper(ctrl *gomock.Controller) *MockKeyMapper {
	mock := &MockKeyMapper{ctrl: ctrl}
	mock.recorder = &MockKeyMapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyMapper) EXPECT() *MockKeyMapperMockRecorder {
	return m.recorder
}

// MergeKeyMap mocks base method.
func (m *MockKeyMapper) MergeKeyMap(arg0 map[term.Event]term.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeKeyMap", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergeKeyMap indicates an expected call of MergeKeyMap.
func (mr *MockKeyMapperMockRecorder) MergeKeyMap(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeKeyMap", reflect.TypeOf((*MockKeyMapper)(nil).MergeKeyMap), arg0)
}

// MockMessenger is a mock of Messenger interface.
type MockMessenger struct {
	ctrl     *gomock.Controller
	recorder *MockMessengerMockRecorder
}

// MockMessengerMockRecorder is the mock recorder for MockMessenger.
type MockMessengerMockRecorder struct {
	mock *MockMessenger
}

// NewMockMessenger creates a new mock instance.
func NewMockMessenger(ctrl *gomock.Controller) *MockMessenger {
	mock := &MockMessenger{ctrl: ctrl}
	mock.recorder = &MockMessengerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessenger) EXPECT() *MockMessengerMockRecorder {
	return m.recorder
}

// SetMessage mocks base method.
func (m *MockMessenger) SetMessage(msg string, args ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetMessage", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMessage indicates an expected call of SetMessage.
func (mr *MockMessengerMockRecorder) SetMessage(msg interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMessage", reflect.TypeOf((*MockMessenger)(nil).SetMessage), varargs...)
}

// MockResourceOpener is a mock of ResourceOpener interface.
type MockResourceOpener struct {
	ctrl     *gomock.Controller
	recorder *MockResourceOpenerMockRecorder
}

// MockResourceOpenerMockRecorder is the mock recorder for MockResourceOpener.
type MockResourceOpenerMockRecorder struct {
	mock *MockResourceOpener
}

// NewMockResourceOpener creates a new mock instance.
func NewMockResourceOpener(ctrl *gomock.Controller) *MockResourceOpener {
	mock := &MockResourceOpener{ctrl: ctrl}
	mock.recorder = &MockResourceOpenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceOpener) EXPECT() *MockResourceOpenerMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockResourceOpener) Open(resource string) (Handler, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", resource)
	ret0, _ := ret[0].(Handler)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockResourceOpenerMockRecorder) Open(resource interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockResourceOpener)(nil).Open), resource)
}

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// PublishInterrupt mocks base method.
func (m *MockEventPublisher) PublishInterrupt() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishInterrupt")
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishInterrupt indicates an expected call of PublishInterrupt.
func (mr *MockEventPublisherMockRecorder) PublishInterrupt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishInterrupt", reflect.TypeOf((*MockEventPublisher)(nil).PublishInterrupt))
}

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockStorage) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockStorageMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStorage)(nil).Close))
}

// Create mocks base method.
func (m *MockStorage) Create(ctx context.Context, ID string, doc interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, ID, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStorageMockRecorder) Create(ctx, ID, doc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStorage)(nil).Create), ctx, ID, doc)
}

// Delete mocks base method.
func (m *MockStorage) Delete(ctx context.Context, ID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, ID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStorageMockRecorder) Delete(ctx, ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStorage)(nil).Delete), ctx, ID)
}

// Get mocks base method.
func (m *MockStorage) Get(ctx context.Context, ID string, doc interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, ID, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockStorageMockRecorder) Get(ctx, ID, doc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStorage)(nil).Get), ctx, ID, doc)
}

// List mocks base method.
func (m *MockStorage) List(ctx context.Context, filters []document.Filter) (document.Iterator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filters)
	ret0, _ := ret[0].(document.Iterator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStorageMockRecorder) List(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStorage)(nil).List), ctx, filters)
}

// Set mocks base method.
func (m *MockStorage) Set(ctx context.Context, ID string, doc interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, ID, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockStorageMockRecorder) Set(ctx, ID, doc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockStorage)(nil).Set), ctx, ID, doc)
}

// Update mocks base method.
func (m *MockStorage) Update(ctx context.Context, ID string, updates []document.Update) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, ID, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStorageMockRecorder) Update(ctx, ID, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStorage)(nil).Update), ctx, ID, updates)
}

// MockBrowser is a mock of Browser interface.
type MockBrowser struct {
	ctrl     *gomock.Controller
	recorder *MockBrowserMockRecorder
}

// MockBrowserMockRecorder is the mock recorder for MockBrowser.
type MockBrowserMockRecorder struct {
	mock *MockBrowser
}

// NewMockBrowser creates a new mock instance.
func NewMockBrowser(ctrl *gomock.Controller) *MockBrowser {
	mock := &MockBrowser{ctrl: ctrl}
	mock.recorder = &MockBrowserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrowser) EXPECT() *MockBrowserMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockBrowser) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockBrowserMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBrowser)(nil).Close))
}

// Create mocks base method.
func (m *MockBrowser) Create(ctx context.Context, ID string, doc interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, ID, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBrowserMockRecorder) Create(ctx, ID, doc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBrowser)(nil).Create), ctx, ID, doc)
}

// Delete mocks base method.
func (m *MockBrowser) Delete(ctx context.Context, ID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, ID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBrowserMockRecorder) Delete(ctx, ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBrowser)(nil).Delete), ctx, ID)
}

// FloatingWindow mocks base method.
func (m *MockBrowser) FloatingWindow(h Handler, at term.Coordinates, width, height int) (Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FloatingWindow", h, at, width, height)
	ret0, _ := ret[0].(Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FloatingWindow indicates an expected call of FloatingWindow.
func (mr *MockBrowserMockRecorder) FloatingWindow(h, at, width, height interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FloatingWindow", reflect.TypeOf((*MockBrowser)(nil).FloatingWindow), h, at, width, height)
}

// Focus mocks base method.
func (m *MockBrowser) Focus() (Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Focus")
	ret0, _ := ret[0].(Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Focus indicates an expected call of Focus.
func (mr *MockBrowserMockRecorder) Focus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Focus", reflect.TypeOf((*MockBrowser)(nil).Focus))
}

// Get mocks base method.
func (m *MockBrowser) Get(ctx context.Context, ID string, doc interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, ID, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockBrowserMockRecorder) Get(ctx, ID, doc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBrowser)(nil).Get), ctx, ID, doc)
}

// List mocks base method.
func (m *MockBrowser) List(ctx context.Context, filters []document.Filter) (document.Iterator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filters)
	ret0, _ := ret[0].(document.Iterator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBrowserMockRecorder) List(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBrowser)(nil).List), ctx, filters)
}

// MergeKeyMap mocks base method.
func (m *MockBrowser) MergeKeyMap(arg0 map[term.Event]term.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeKeyMap", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergeKeyMap indicates an expected call of MergeKeyMap.
func (mr *MockBrowserMockRecorder) MergeKeyMap(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeKeyMap", reflect.TypeOf((*MockBrowser)(nil).MergeKeyMap), arg0)
}

// Open mocks base method.
func (m *MockBrowser) Open(resource string) (Handler, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", resource)
	ret0, _ := ret[0].(Handler)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockBrowserMockRecorder) Open(resource interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockBrowser)(nil).Open), resource)
}

// PublishInterrupt mocks base method.
func (m *MockBrowser) PublishInterrupt() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishInterrupt")
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishInterrupt indicates an expected call of PublishInterrupt.
func (mr *MockBrowserMockRecorder) PublishInterrupt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishInterrupt", reflect.TypeOf((*MockBrowser)(nil).PublishInterrupt))
}

// Set mocks base method.
func (m *MockBrowser) Set(ctx context.Context, ID string, doc interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, ID, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockBrowserMockRecorder) Set(ctx, ID, doc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockBrowser)(nil).Set), ctx, ID, doc)
}

// SetMessage mocks base method.
func (m *MockBrowser) SetMessage(msg string, args ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetMessage", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMessage indicates an expected call of SetMessage.
func (mr *MockBrowserMockRecorder) SetMessage(msg interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMessage", reflect.TypeOf((*MockBrowser)(nil).SetMessage), varargs...)
}

// SplitHorizontalAbove mocks base method.
func (m *MockBrowser) SplitHorizontalAbove(arg0 Handler) (Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SplitHorizontalAbove", arg0)
	ret0, _ := ret[0].(Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SplitHorizontalAbove indicates an expected call of SplitHorizontalAbove.
func (mr *MockBrowserMockRecorder) SplitHorizontalAbove(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SplitHorizontalAbove", reflect.TypeOf((*MockBrowser)(nil).SplitHorizontalAbove), arg0)
}

// SplitHorizontalBelow mocks base method.
func (m *MockBrowser) SplitHorizontalBelow(arg0 Handler) (Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SplitHorizontalBelow", arg0)
	ret0, _ := ret[0].(Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SplitHorizontalBelow indicates an expected call of SplitHorizontalBelow.
func (mr *MockBrowserMockRecorder) SplitHorizontalBelow(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SplitHorizontalBelow", reflect.TypeOf((*MockBrowser)(nil).SplitHorizontalBelow), arg0)
}

// SplitVerticalLeft mocks base method.
func (m *MockBrowser) SplitVerticalLeft(arg0 Handler) (Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SplitVerticalLeft", arg0)
	ret0, _ := ret[0].(Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SplitVerticalLeft indicates an expected call of SplitVerticalLeft.
func (mr *MockBrowserMockRecorder) SplitVerticalLeft(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SplitVerticalLeft", reflect.TypeOf((*MockBrowser)(nil).SplitVerticalLeft), arg0)
}

// SplitVerticalRight mocks base method.
func (m *MockBrowser) SplitVerticalRight(arg0 Handler) (Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SplitVerticalRight", arg0)
	ret0, _ := ret[0].(Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SplitVerticalRight indicates an expected call of SplitVerticalRight.
func (mr *MockBrowserMockRecorder) SplitVerticalRight(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SplitVerticalRight", reflect.TypeOf((*MockBrowser)(nil).SplitVerticalRight), arg0)
}

// Subscribe mocks base method.
func (m *MockBrowser) Subscribe(arg0 term.Event, arg1 EventHandler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockBrowserMockRecorder) Subscribe(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockBrowser)(nil).Subscribe), arg0, arg1)
}

// Update mocks base method.
func (m *MockBrowser) Update(ctx context.Context, ID string, updates []document.Update) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, ID, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBrowserMockRecorder) Update(ctx, ID, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBrowser)(nil).Update), ctx, ID, updates)
}
