// Unstable Build LLC ("COMPANY") CONFIDENTIAL
//
// Unpublished Copyright (c) 2017-2026 Unstable Build, All Rights Reserved.
//
// NOTICE: All information contained herein is, and remains the property of COMPANY.
// The intellectual and technical concepts contained herein are proprietary to
// COMPANY and may be covered by U.S. and Foreign Patents, patents in process,
// and are protected by trade secret or copyright law. Dissemination of this information
// or reproduction of this material is strictly forbidden unless prior written permission
// is obtained from COMPANY. Access to the source code contained herein is hereby
// forbidden to anyone except current COMPANY employees, managers or contractors who
// have executed Confidentiality and Non-disclosure agreements explicitly covering such access.
//
// The copyright notice above does not evidence any actual or intended publication or
// disclosure of this source code, which includes information that is confidential and/or
// proprietary, and is a trade secret, of COMPANY. ANY REPRODUCTION, MODIFICATION,
// DISTRIBUTION, PUBLIC  PERFORMANCE, OR PUBLIC DISPLAY OF OR THROUGH USE OF THIS SOURCE CODE
// WITHOUT  THE EXPRESS WRITTEN CONSENT OF COMPANY IS STRICTLY PROHIBITED, AND IN
// VIOLATION OF APPLICABLE LAWS AND INTERNATIONAL TREATIES. THE RECEIPT OR POSSESSION OF
// THIS SOURCE CODE AND/OR RELATED INFORMATION DOES NOT CONVEY OR IMPLY ANY RIGHTS TO
// REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS, OR TO MANUFACTURE, USE, OR SELL
// ANYTHING THAT IT MAY DESCRIBE, IN WHOLE OR IN PART.

package template

import (
	"fmt"
	"strings"

	"github.com/unstablebuild/rune-go-sdk/term"
	"github.com/unstablebuild/rune-go-sdk/component"
	"github.com/unstablebuild/rune-go-sdk/term/graphemecluster"
	"github.com/unstablebuild/tcell/v3"
)

// Build builds a component from a template string, value
// and attributes generated by Parse.
func Build(
	template string, value any, attrs, defAttrs term.Attributes,
	bgColor tcell.Color,
) []component.Floating {
	if attrs.Bg == 0 && attrs.Fg == 0 {
		attrs = defAttrs
	}
	attrs.Attrs |= defAttrs.Attrs
	cfg := component.StringConfig{
		Alignment: component.AlignmentCentered,
	}
	cfg.Attributes = attrs
	if cfg.Attributes.Bg == 0 {
		cfg.Attributes.Bg = bgColor
	}
	cfg.BackgroundAttributes.Bg = cfg.Attributes.Bg
	backgroundRunesCfg := cfg
	backgroundRunesCfg.Fg = cfg.Attributes.Bg
	backgroundRunesCfg.Bg = bgColor

	var components []component.Floating
	var buf strings.Builder
	var currentBackground bool
	// invert background/foreground if template chunk has background runes
	for i, r := range template {
		isBackground := graphemecluster.IsBackground(r)
		if i == 0 {
			currentBackground = isBackground
		}
		switch {
		case isBackground && currentBackground:
			buf.WriteRune(r)
		case !isBackground && !currentBackground:
			buf.WriteRune(r)
		case !isBackground && currentBackground:
			components = appendComponent(components, &buf, value, backgroundRunesCfg)
			currentBackground = isBackground
			buf.Reset()
			buf.WriteRune(r)
		case isBackground && !currentBackground:
			components = appendComponent(components, &buf, value, cfg)
			currentBackground = isBackground
			buf.Reset()
			buf.WriteRune(r)
		}
	}
	if currentBackground {
		components = appendComponent(components, &buf, value, backgroundRunesCfg)
	} else {
		components = appendComponent(components, &buf, value, cfg)
	}
	return components
}

func appendComponent(
	components []component.Floating, buf *strings.Builder,
	value any, cfg component.StringConfig,
) []component.Floating {
	str := buf.String()
	if strings.Contains(str, "%s") || strings.Contains(str, "%d") {
		str = fmt.Sprintf(str, value)
	}
	components = append(components,
		component.NewStringWithConfig(str, cfg),
	)
	return components
}
