// Code generated by MockGen. DO NOT EDIT.
// Source: ./plugin/clipboard.go

// Package plugin is a generated GoMock package.
package plugin

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClipboardRegister is a mock of ClipboardRegister interface.
type MockClipboardRegister struct {
	ctrl     *gomock.Controller
	recorder *MockClipboardRegisterMockRecorder
}

// MockClipboardRegisterMockRecorder is the mock recorder for MockClipboardRegister.
type MockClipboardRegisterMockRecorder struct {
	mock *MockClipboardRegister
}

// NewMockClipboardRegister creates a new mock instance.
func NewMockClipboardRegister(ctrl *gomock.Controller) *MockClipboardRegister {
	mock := &MockClipboardRegister{ctrl: ctrl}
	mock.recorder = &MockClipboardRegisterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClipboardRegister) EXPECT() *MockClipboardRegisterMockRecorder {
	return m.recorder
}

// Copy mocks base method.
func (m *MockClipboardRegister) Copy(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Copy indicates an expected call of Copy.
func (mr *MockClipboardRegisterMockRecorder) Copy(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockClipboardRegister)(nil).Copy), arg0)
}

// Paste mocks base method.
func (m *MockClipboardRegister) Paste() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Paste")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Paste indicates an expected call of Paste.
func (mr *MockClipboardRegisterMockRecorder) Paste() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Paste", reflect.TypeOf((*MockClipboardRegister)(nil).Paste))
}

// MockClipboardSetter is a mock of ClipboardSetter interface.
type MockClipboardSetter struct {
	ctrl     *gomock.Controller
	recorder *MockClipboardSetterMockRecorder
}

// MockClipboardSetterMockRecorder is the mock recorder for MockClipboardSetter.
type MockClipboardSetterMockRecorder struct {
	mock *MockClipboardSetter
}

// NewMockClipboardSetter creates a new mock instance.
func NewMockClipboardSetter(ctrl *gomock.Controller) *MockClipboardSetter {
	mock := &MockClipboardSetter{ctrl: ctrl}
	mock.recorder = &MockClipboardSetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClipboardSetter) EXPECT() *MockClipboardSetterMockRecorder {
	return m.recorder
}

// SetRegister mocks base method.
func (m *MockClipboardSetter) SetRegister(registerID string, r ClipboardRegister) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRegister", registerID, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRegister indicates an expected call of SetRegister.
func (mr *MockClipboardSetterMockRecorder) SetRegister(registerID, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRegister", reflect.TypeOf((*MockClipboardSetter)(nil).SetRegister), registerID, r)
}

// MockClipboard is a mock of Clipboard interface.
type MockClipboard struct {
	ctrl     *gomock.Controller
	recorder *MockClipboardMockRecorder
}

// MockClipboardMockRecorder is the mock recorder for MockClipboard.
type MockClipboardMockRecorder struct {
	mock *MockClipboard
}

// NewMockClipboard creates a new mock instance.
func NewMockClipboard(ctrl *gomock.Controller) *MockClipboard {
	mock := &MockClipboard{ctrl: ctrl}
	mock.recorder = &MockClipboardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClipboard) EXPECT() *MockClipboardMockRecorder {
	return m.recorder
}

// Copy mocks base method.
func (m *MockClipboard) Copy(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Copy indicates an expected call of Copy.
func (mr *MockClipboardMockRecorder) Copy(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockClipboard)(nil).Copy), arg0)
}

// Paste mocks base method.
func (m *MockClipboard) Paste() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Paste")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Paste indicates an expected call of Paste.
func (mr *MockClipboardMockRecorder) Paste() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Paste", reflect.TypeOf((*MockClipboard)(nil).Paste))
}

// SetRegister mocks base method.
func (m *MockClipboard) SetRegister(registerID string, r ClipboardRegister) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRegister", registerID, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRegister indicates an expected call of SetRegister.
func (mr *MockClipboardMockRecorder) SetRegister(registerID, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRegister", reflect.TypeOf((*MockClipboard)(nil).SetRegister), registerID, r)
}
