// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: rpc/editor.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	rpc "unstable.build/go-tui/term/rpc"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EditorEvent_Type int32

const (
	EditorEvent_TypeOpen    EditorEvent_Type = 0
	EditorEvent_TypeClose   EditorEvent_Type = 1
	EditorEvent_TypeFlush   EditorEvent_Type = 2
	EditorEvent_TypeEdit    EditorEvent_Type = 3
	EditorEvent_TypeCommand EditorEvent_Type = 4
	EditorEvent_TypeScroll  EditorEvent_Type = 5
	EditorEvent_TypeFocus   EditorEvent_Type = 6
	EditorEvent_TypeUnfocus EditorEvent_Type = 7
	EditorEvent_TypeCursor  EditorEvent_Type = 8
)

// Enum value maps for EditorEvent_Type.
var (
	EditorEvent_Type_name = map[int32]string{
		0: "TypeOpen",
		1: "TypeClose",
		2: "TypeFlush",
		3: "TypeEdit",
		4: "TypeCommand",
		5: "TypeScroll",
		6: "TypeFocus",
		7: "TypeUnfocus",
		8: "TypeCursor",
	}
	EditorEvent_Type_value = map[string]int32{
		"TypeOpen":    0,
		"TypeClose":   1,
		"TypeFlush":   2,
		"TypeEdit":    3,
		"TypeCommand": 4,
		"TypeScroll":  5,
		"TypeFocus":   6,
		"TypeUnfocus": 7,
		"TypeCursor":  8,
	}
)

func (x EditorEvent_Type) Enum() *EditorEvent_Type {
	p := new(EditorEvent_Type)
	*p = x
	return p
}

func (x EditorEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EditorEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_editor_proto_enumTypes[0].Descriptor()
}

func (EditorEvent_Type) Type() protoreflect.EnumType {
	return &file_rpc_editor_proto_enumTypes[0]
}

func (x EditorEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EditorEvent_Type.Descriptor instead.
func (EditorEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{3, 0}
}

type URI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
}

func (x *URI) Reset() {
	*x = URI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URI) ProtoMessage() {}

func (x *URI) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URI.ProtoReflect.Descriptor instead.
func (*URI) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{0}
}

func (x *URI) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type EditRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceName *URI           `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Buffer       []*rpc.CellRow `protobuf:"bytes,2,rep,name=buffer,proto3" json:"buffer,omitempty"`
}

func (x *EditRequest) Reset() {
	*x = EditRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditRequest) ProtoMessage() {}

func (x *EditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditRequest.ProtoReflect.Descriptor instead.
func (*EditRequest) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{1}
}

func (x *EditRequest) GetResourceName() *URI {
	if x != nil {
		return x.ResourceName
	}
	return nil
}

func (x *EditRequest) GetBuffer() []*rpc.CellRow {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type EditResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EditResponse) Reset() {
	*x = EditResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditResponse) ProtoMessage() {}

func (x *EditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditResponse.ProtoReflect.Descriptor instead.
func (*EditResponse) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{2}
}

type EditorEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type         EditorEvent_Type `protobuf:"varint,1,opt,name=type,proto3,enum=text.EditorEvent_Type" json:"type,omitempty"`
	ResourceName *URI             `protobuf:"bytes,2,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Start        *rpc.Coordinates `protobuf:"bytes,4,opt,name=start,proto3" json:"start,omitempty"`
	End          *rpc.Coordinates `protobuf:"bytes,5,opt,name=end,proto3" json:"end,omitempty"`
	From         *rpc.Coordinates `protobuf:"bytes,6,opt,name=from,proto3" json:"from,omitempty"`
	To           *rpc.Coordinates `protobuf:"bytes,7,opt,name=to,proto3" json:"to,omitempty"`
	Content      string           `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *EditorEvent) Reset() {
	*x = EditorEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditorEvent) ProtoMessage() {}

func (x *EditorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditorEvent.ProtoReflect.Descriptor instead.
func (*EditorEvent) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{3}
}

func (x *EditorEvent) GetType() EditorEvent_Type {
	if x != nil {
		return x.Type
	}
	return EditorEvent_TypeOpen
}

func (x *EditorEvent) GetResourceName() *URI {
	if x != nil {
		return x.ResourceName
	}
	return nil
}

func (x *EditorEvent) GetStart() *rpc.Coordinates {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *EditorEvent) GetEnd() *rpc.Coordinates {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *EditorEvent) GetFrom() *rpc.Coordinates {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *EditorEvent) GetTo() *rpc.Coordinates {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *EditorEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type EditorSubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        []EditorEvent_Type `protobuf:"varint,1,rep,packed,name=type,proto3,enum=text.EditorEvent_Type" json:"type,omitempty"`
	Unsubscribe bool               `protobuf:"varint,3,opt,name=unsubscribe,proto3" json:"unsubscribe,omitempty"`
}

func (x *EditorSubscribeRequest) Reset() {
	*x = EditorSubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditorSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditorSubscribeRequest) ProtoMessage() {}

func (x *EditorSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditorSubscribeRequest.ProtoReflect.Descriptor instead.
func (*EditorSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{4}
}

func (x *EditorSubscribeRequest) GetType() []EditorEvent_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *EditorSubscribeRequest) GetUnsubscribe() bool {
	if x != nil {
		return x.Unsubscribe
	}
	return false
}

type SetLocationListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceName *URI                               `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	ListId       string                             `protobuf:"bytes,2,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	Locations    []*SetLocationListRequest_Location `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`
	Priority     uint32                             `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
}

func (x *SetLocationListRequest) Reset() {
	*x = SetLocationListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLocationListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLocationListRequest) ProtoMessage() {}

func (x *SetLocationListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLocationListRequest.ProtoReflect.Descriptor instead.
func (*SetLocationListRequest) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{5}
}

func (x *SetLocationListRequest) GetResourceName() *URI {
	if x != nil {
		return x.ResourceName
	}
	return nil
}

func (x *SetLocationListRequest) GetListId() string {
	if x != nil {
		return x.ListId
	}
	return ""
}

func (x *SetLocationListRequest) GetLocations() []*SetLocationListRequest_Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *SetLocationListRequest) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type SetLocationListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetLocationListResponse) Reset() {
	*x = SetLocationListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLocationListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLocationListResponse) ProtoMessage() {}

func (x *SetLocationListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLocationListResponse.ProtoReflect.Descriptor instead.
func (*SetLocationListResponse) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{6}
}

type EditCellRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceName *URI             `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Start        *rpc.Coordinates `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End          *rpc.Coordinates `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	Str          string           `protobuf:"bytes,4,opt,name=str,proto3" json:"str,omitempty"`
}

func (x *EditCellRequest) Reset() {
	*x = EditCellRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCellRequest) ProtoMessage() {}

func (x *EditCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCellRequest.ProtoReflect.Descriptor instead.
func (*EditCellRequest) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{7}
}

func (x *EditCellRequest) GetResourceName() *URI {
	if x != nil {
		return x.ResourceName
	}
	return nil
}

func (x *EditCellRequest) GetStart() *rpc.Coordinates {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *EditCellRequest) GetEnd() *rpc.Coordinates {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *EditCellRequest) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

type EditCellResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From *rpc.Coordinates `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To   *rpc.Coordinates `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Old  string           `protobuf:"bytes,3,opt,name=old,proto3" json:"old,omitempty"`
}

func (x *EditCellResponse) Reset() {
	*x = EditCellResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditCellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCellResponse) ProtoMessage() {}

func (x *EditCellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCellResponse.ProtoReflect.Descriptor instead.
func (*EditCellResponse) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{8}
}

func (x *EditCellResponse) GetFrom() *rpc.Coordinates {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *EditCellResponse) GetTo() *rpc.Coordinates {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *EditCellResponse) GetOld() string {
	if x != nil {
		return x.Old
	}
	return ""
}

type RawCellsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceName *URI `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
}

func (x *RawCellsRequest) Reset() {
	*x = RawCellsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawCellsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawCellsRequest) ProtoMessage() {}

func (x *RawCellsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawCellsRequest.ProtoReflect.Descriptor instead.
func (*RawCellsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{9}
}

func (x *RawCellsRequest) GetResourceName() *URI {
	if x != nil {
		return x.ResourceName
	}
	return nil
}

type RawCellsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows []*rpc.CellRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
}

func (x *RawCellsResponse) Reset() {
	*x = RawCellsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawCellsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawCellsResponse) ProtoMessage() {}

func (x *RawCellsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawCellsResponse.ProtoReflect.Descriptor instead.
func (*RawCellsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{10}
}

func (x *RawCellsResponse) GetRows() []*rpc.CellRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type MoveToLocationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceName *URI   `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	ListId       string `protobuf:"bytes,2,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
}

func (x *MoveToLocationRequest) Reset() {
	*x = MoveToLocationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveToLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToLocationRequest) ProtoMessage() {}

func (x *MoveToLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToLocationRequest.ProtoReflect.Descriptor instead.
func (*MoveToLocationRequest) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{11}
}

func (x *MoveToLocationRequest) GetResourceName() *URI {
	if x != nil {
		return x.ResourceName
	}
	return nil
}

func (x *MoveToLocationRequest) GetListId() string {
	if x != nil {
		return x.ListId
	}
	return ""
}

type MoveToLocationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MoveToLocationResponse) Reset() {
	*x = MoveToLocationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveToLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToLocationResponse) ProtoMessage() {}

func (x *MoveToLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToLocationResponse.ProtoReflect.Descriptor instead.
func (*MoveToLocationResponse) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{12}
}

type RegisterCommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command   *CommandManual `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	ChannelId string         `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (x *RegisterCommandRequest) Reset() {
	*x = RegisterCommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCommandRequest) ProtoMessage() {}

func (x *RegisterCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCommandRequest.ProtoReflect.Descriptor instead.
func (*RegisterCommandRequest) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterCommandRequest) GetCommand() *CommandManual {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *RegisterCommandRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type CommandManual struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Summary  string           `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Synopsis string           `protobuf:"bytes,3,opt,name=synopsis,proto3" json:"synopsis,omitempty"`
	Commands []*CommandManual `protobuf:"bytes,4,rep,name=commands,proto3" json:"commands,omitempty"`
}

func (x *CommandManual) Reset() {
	*x = CommandManual{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandManual) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandManual) ProtoMessage() {}

func (x *CommandManual) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandManual.ProtoReflect.Descriptor instead.
func (*CommandManual) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{14}
}

func (x *CommandManual) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandManual) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CommandManual) GetSynopsis() string {
	if x != nil {
		return x.Synopsis
	}
	return ""
}

func (x *CommandManual) GetCommands() []*CommandManual {
	if x != nil {
		return x.Commands
	}
	return nil
}

type RegisterCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterCommandResponse) Reset() {
	*x = RegisterCommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCommandResponse) ProtoMessage() {}

func (x *RegisterCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCommandResponse.ProtoReflect.Descriptor instead.
func (*RegisterCommandResponse) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{15}
}

type SetCursorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos          *rpc.Coordinates `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`
	ResourceName *URI             `protobuf:"bytes,2,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
}

func (x *SetCursorRequest) Reset() {
	*x = SetCursorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetCursorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCursorRequest) ProtoMessage() {}

func (x *SetCursorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCursorRequest.ProtoReflect.Descriptor instead.
func (*SetCursorRequest) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{16}
}

func (x *SetCursorRequest) GetPos() *rpc.Coordinates {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *SetCursorRequest) GetResourceName() *URI {
	if x != nil {
		return x.ResourceName
	}
	return nil
}

type SetCursorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetCursorResponse) Reset() {
	*x = SetCursorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetCursorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCursorResponse) ProtoMessage() {}

func (x *SetCursorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCursorResponse.ProtoReflect.Descriptor instead.
func (*SetCursorResponse) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{17}
}

type CursorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceName *URI `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
}

func (x *CursorRequest) Reset() {
	*x = CursorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CursorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorRequest) ProtoMessage() {}

func (x *CursorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorRequest.ProtoReflect.Descriptor instead.
func (*CursorRequest) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{18}
}

func (x *CursorRequest) GetResourceName() *URI {
	if x != nil {
		return x.ResourceName
	}
	return nil
}

type CursorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos *rpc.Coordinates `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`
}

func (x *CursorResponse) Reset() {
	*x = CursorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CursorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorResponse) ProtoMessage() {}

func (x *CursorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorResponse.ProtoReflect.Descriptor instead.
func (*CursorResponse) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{19}
}

func (x *CursorResponse) GetPos() *rpc.Coordinates {
	if x != nil {
		return x.Pos
	}
	return nil
}

type EditorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceName *URI `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
}

func (x *EditorRequest) Reset() {
	*x = EditorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditorRequest) ProtoMessage() {}

func (x *EditorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditorRequest.ProtoReflect.Descriptor instead.
func (*EditorRequest) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{20}
}

func (x *EditorRequest) GetResourceName() *URI {
	if x != nil {
		return x.ResourceName
	}
	return nil
}

type EditorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EditorResponse) Reset() {
	*x = EditorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditorResponse) ProtoMessage() {}

func (x *EditorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditorResponse.ProtoReflect.Descriptor instead.
func (*EditorResponse) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{21}
}

type SetDefaultAttributesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceName *URI            `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Attributes   *rpc.Attributes `protobuf:"bytes,2,opt,name=attributes,proto3" json:"attributes,omitempty"`
}

func (x *SetDefaultAttributesRequest) Reset() {
	*x = SetDefaultAttributesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDefaultAttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultAttributesRequest) ProtoMessage() {}

func (x *SetDefaultAttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultAttributesRequest.ProtoReflect.Descriptor instead.
func (*SetDefaultAttributesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{22}
}

func (x *SetDefaultAttributesRequest) GetResourceName() *URI {
	if x != nil {
		return x.ResourceName
	}
	return nil
}

func (x *SetDefaultAttributesRequest) GetAttributes() *rpc.Attributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type SetDefaultAttributesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetDefaultAttributesResponse) Reset() {
	*x = SetDefaultAttributesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDefaultAttributesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultAttributesResponse) ProtoMessage() {}

func (x *SetDefaultAttributesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultAttributesResponse.ProtoReflect.Descriptor instead.
func (*SetDefaultAttributesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{23}
}

type HandleCommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args          []string         `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	ResourceName  *URI             `protobuf:"bytes,3,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	CursorContent *rpc.Coordinates `protobuf:"bytes,4,opt,name=cursor_content,json=cursorContent,proto3" json:"cursor_content,omitempty"`
	CursorWindow  *rpc.Coordinates `protobuf:"bytes,5,opt,name=cursor_window,json=cursorWindow,proto3" json:"cursor_window,omitempty"`
	WindowId      uint64           `protobuf:"varint,6,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
}

func (x *HandleCommandRequest) Reset() {
	*x = HandleCommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleCommandRequest) ProtoMessage() {}

func (x *HandleCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleCommandRequest.ProtoReflect.Descriptor instead.
func (*HandleCommandRequest) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{24}
}

func (x *HandleCommandRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HandleCommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *HandleCommandRequest) GetResourceName() *URI {
	if x != nil {
		return x.ResourceName
	}
	return nil
}

func (x *HandleCommandRequest) GetCursorContent() *rpc.Coordinates {
	if x != nil {
		return x.CursorContent
	}
	return nil
}

func (x *HandleCommandRequest) GetCursorWindow() *rpc.Coordinates {
	if x != nil {
		return x.CursorWindow
	}
	return nil
}

func (x *HandleCommandRequest) GetWindowId() uint64 {
	if x != nil {
		return x.WindowId
	}
	return 0
}

type HandleCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exit bool `protobuf:"varint,1,opt,name=exit,proto3" json:"exit,omitempty"`
}

func (x *HandleCommandResponse) Reset() {
	*x = HandleCommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleCommandResponse) ProtoMessage() {}

func (x *HandleCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleCommandResponse.ProtoReflect.Descriptor instead.
func (*HandleCommandResponse) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{25}
}

func (x *HandleCommandResponse) GetExit() bool {
	if x != nil {
		return x.Exit
	}
	return false
}

type SetLocationListRequest_Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From *rpc.Coordinates `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To   *rpc.Coordinates `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Attr *rpc.Attributes  `protobuf:"bytes,3,opt,name=attr,proto3" json:"attr,omitempty"`
	Msg  string           `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SetLocationListRequest_Location) Reset() {
	*x = SetLocationListRequest_Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_editor_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLocationListRequest_Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLocationListRequest_Location) ProtoMessage() {}

func (x *SetLocationListRequest_Location) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_editor_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLocationListRequest_Location.ProtoReflect.Descriptor instead.
func (*SetLocationListRequest_Location) Descriptor() ([]byte, []int) {
	return file_rpc_editor_proto_rawDescGZIP(), []int{5, 0}
}

func (x *SetLocationListRequest_Location) GetFrom() *rpc.Coordinates {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *SetLocationListRequest_Location) GetTo() *rpc.Coordinates {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SetLocationListRequest_Location) GetAttr() *rpc.Attributes {
	if x != nil {
		return x.Attr
	}
	return nil
}

func (x *SetLocationListRequest_Location) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_rpc_editor_proto protoreflect.FileDescriptor

var file_rpc_editor_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x70, 0x63, 0x2f, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x74, 0x65, 0x78, 0x74, 0x1a, 0x13, 0x74, 0x65, 0x72, 0x6d, 0x2f, 0x72,
	0x70, 0x63, 0x2f, 0x74, 0x65, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x17, 0x0a,
	0x03, 0x55, 0x52, 0x49, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x22, 0x64, 0x0a, 0x0b, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x74,
	0x65, 0x78, 0x74, 0x2e, 0x55, 0x52, 0x49, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x2e, 0x43, 0x65, 0x6c,
	0x6c, 0x52, 0x6f, 0x77, 0x52, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x22, 0x0e, 0x0a, 0x0c,
	0x45, 0x64, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xaf, 0x03, 0x0a,
	0x0b, 0x45, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x74, 0x65, 0x78,
	0x74, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2e, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x55, 0x52, 0x49, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x2e, 0x43,
	0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x12, 0x23, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x74, 0x65, 0x72, 0x6d, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65,
	0x73, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x25, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x2e, 0x43, 0x6f, 0x6f, 0x72,
	0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x21, 0x0a,
	0x02, 0x74, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x65, 0x72, 0x6d,
	0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x02, 0x74, 0x6f,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x91, 0x01, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x79, 0x70, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x10,
	0x00, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x79, 0x70, 0x65, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x10, 0x01,
	0x12, 0x0d, 0x0a, 0x09, 0x54, 0x79, 0x70, 0x65, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x10, 0x02, 0x12,
	0x0c, 0x0a, 0x08, 0x54, 0x79, 0x70, 0x65, 0x45, 0x64, 0x69, 0x74, 0x10, 0x03, 0x12, 0x0f, 0x0a,
	0x0b, 0x54, 0x79, 0x70, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x10, 0x04, 0x12, 0x0e,
	0x0a, 0x0a, 0x54, 0x79, 0x70, 0x65, 0x53, 0x63, 0x72, 0x6f, 0x6c, 0x6c, 0x10, 0x05, 0x12, 0x0d,
	0x0a, 0x09, 0x54, 0x79, 0x70, 0x65, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x10, 0x06, 0x12, 0x0f, 0x0a,
	0x0b, 0x54, 0x79, 0x70, 0x65, 0x55, 0x6e, 0x66, 0x6f, 0x63, 0x75, 0x73, 0x10, 0x07, 0x12, 0x0e,
	0x0a, 0x0a, 0x54, 0x79, 0x70, 0x65, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x10, 0x08, 0x22, 0x66,
	0x0a, 0x16, 0x45, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x45, 0x64,
	0x69, 0x74, 0x6f, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x75, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x75, 0x6e, 0x73, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x22, 0xd1, 0x02, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2e, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e,
	0x55, 0x52, 0x49, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x12, 0x43, 0x0a, 0x09, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x74, 0x65, 0x78, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x1a, 0x8c, 0x01, 0x0a, 0x08,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x2e, 0x43, 0x6f,
	0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12,
	0x21, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x65,
	0x72, 0x6d, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x02,
	0x74, 0x6f, 0x12, 0x24, 0x0a, 0x04, 0x61, 0x74, 0x74, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x73, 0x52, 0x04, 0x61, 0x74, 0x74, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x19, 0x0a, 0x17, 0x53, 0x65,
	0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xa1, 0x01, 0x0a, 0x0f, 0x45, 0x64, 0x69, 0x74, 0x43, 0x65,
	0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0d, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x55, 0x52, 0x49, 0x52, 0x0c, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x2e,
	0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x23, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x73, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x74, 0x72, 0x22, 0x6e, 0x0a, 0x10, 0x45, 0x64, 0x69,
	0x74, 0x43, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x65,
	0x72, 0x6d, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x04,
	0x66, 0x72, 0x6f, 0x6d, 0x12, 0x21, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61,
	0x74, 0x65, 0x73, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x6c, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x6c, 0x64, 0x22, 0x41, 0x0a, 0x0f, 0x52, 0x61, 0x77,
	0x43, 0x65, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0d,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x55, 0x52, 0x49, 0x52, 0x0c,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x35, 0x0a, 0x10,
	0x52, 0x61, 0x77, 0x43, 0x65, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x21, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x74, 0x65, 0x72, 0x6d, 0x2e, 0x43, 0x65, 0x6c, 0x6c, 0x52, 0x6f, 0x77, 0x52, 0x04, 0x72,
	0x6f, 0x77, 0x73, 0x22, 0x60, 0x0a, 0x15, 0x4d, 0x6f, 0x76, 0x65, 0x54, 0x6f, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0d,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x55, 0x52, 0x49, 0x52, 0x0c,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c,
	0x69, 0x73, 0x74, 0x49, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x4d, 0x6f, 0x76, 0x65, 0x54, 0x6f, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x66, 0x0a, 0x16, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x65, 0x78,
	0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x52,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x8a, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x79, 0x6e, 0x6f, 0x70,
	0x73, 0x69, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x79, 0x6e, 0x6f, 0x70,
	0x73, 0x69, 0x73, 0x12, 0x2f, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x4d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x73, 0x22, 0x19, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x67, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61,
	0x74, 0x65, 0x73, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x2e, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x55, 0x52, 0x49, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x43,
	0x75, 0x72, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3f, 0x0a,
	0x0d, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e,
	0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x55, 0x52, 0x49,
	0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x35,
	0x0a, 0x0e, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x23, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x74, 0x65, 0x72, 0x6d, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73,
	0x52, 0x03, 0x70, 0x6f, 0x73, 0x22, 0x3f, 0x0a, 0x0d, 0x45, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x74, 0x65, 0x78, 0x74, 0x2e, 0x55, 0x52, 0x49, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x45, 0x64, 0x69, 0x74, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x7f, 0x0a, 0x1b, 0x53, 0x65, 0x74, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x55, 0x52, 0x49, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x65,
	0x72, 0x6d, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x52, 0x0a, 0x61,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x22, 0x1e, 0x0a, 0x1c, 0x53, 0x65, 0x74,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xfd, 0x01, 0x0a, 0x14, 0x48, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x2e, 0x0a, 0x0d, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x55, 0x52, 0x49, 0x52, 0x0c, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x0e, 0x63, 0x75,
	0x72, 0x73, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x65, 0x72, 0x6d, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69,
	0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x0d, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x36, 0x0a, 0x0d, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x5f, 0x77,
	0x69, 0x6e, 0x64, 0x6f, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x65,
	0x72, 0x6d, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x0c,
	0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x12, 0x1b, 0x0a, 0x09,
	0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x49, 0x64, 0x22, 0x2b, 0x0a, 0x15, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x78, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x04, 0x65, 0x78, 0x69, 0x74, 0x32, 0xb1, 0x06, 0x0a, 0x06, 0x45, 0x64, 0x69, 0x74, 0x6f,
	0x72, 0x12, 0x2d, 0x0a, 0x04, 0x45, 0x64, 0x69, 0x74, 0x12, 0x11, 0x2e, 0x74, 0x65, 0x78, 0x74,
	0x2e, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x74,
	0x65, 0x78, 0x74, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x47, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x74,
	0x65, 0x78, 0x74, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x74, 0x65, 0x78,
	0x74, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x09, 0x53, 0x65, 0x74,
	0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x16, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x53, 0x65,
	0x74, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17,
	0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x43, 0x75, 0x72, 0x73, 0x6f,
	0x72, 0x12, 0x13, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x43, 0x75,
	0x72, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06,
	0x45, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x13, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x45, 0x64,
	0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x74, 0x65,
	0x78, 0x74, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4e, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4f, 0x0a, 0x12, 0x4d, 0x6f, 0x76, 0x65, 0x54, 0x6f, 0x4e, 0x65, 0x78, 0x74, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x4d,
	0x6f, 0x76, 0x65, 0x54, 0x6f, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x4d, 0x6f, 0x76, 0x65,
	0x54, 0x6f, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4f, 0x0a, 0x12, 0x4d, 0x6f, 0x76, 0x65, 0x54, 0x6f, 0x50, 0x72, 0x65, 0x76,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e,
	0x4d, 0x6f, 0x76, 0x65, 0x54, 0x6f, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x4d, 0x6f, 0x76,
	0x65, 0x54, 0x6f, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x08, 0x45, 0x64, 0x69, 0x74, 0x43, 0x65, 0x6c, 0x6c, 0x12,
	0x15, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x43, 0x65, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x45, 0x64,
	0x69, 0x74, 0x43, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39,
	0x0a, 0x08, 0x52, 0x61, 0x77, 0x43, 0x65, 0x6c, 0x6c, 0x73, 0x12, 0x15, 0x2e, 0x74, 0x65, 0x78,
	0x74, 0x2e, 0x52, 0x61, 0x77, 0x43, 0x65, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x52, 0x61, 0x77, 0x43, 0x65, 0x6c, 0x6c,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x14, 0x53, 0x65, 0x74,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x73, 0x12, 0x21, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x44, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x1c, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x45, 0x64, 0x69,
	0x74, 0x6f, 0x72, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x6f,
	0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x28, 0x01, 0x30, 0x01, 0x32, 0x5a, 0x0a, 0x0e, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x48, 0x0a, 0x0d,
	0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1a, 0x2e,
	0x74, 0x65, 0x78, 0x74, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x74, 0x65, 0x78, 0x74,
	0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x20, 0x5a, 0x1e, 0x75, 0x6e, 0x73, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x67, 0x6f, 0x2d, 0x74, 0x75, 0x69, 0x2f,
	0x74, 0x65, 0x78, 0x74, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_editor_proto_rawDescOnce sync.Once
	file_rpc_editor_proto_rawDescData = file_rpc_editor_proto_rawDesc
)

func file_rpc_editor_proto_rawDescGZIP() []byte {
	file_rpc_editor_proto_rawDescOnce.Do(func() {
		file_rpc_editor_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_editor_proto_rawDescData)
	})
	return file_rpc_editor_proto_rawDescData
}

var file_rpc_editor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_editor_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_rpc_editor_proto_goTypes = []interface{}{
	(EditorEvent_Type)(0),                   // 0: text.EditorEvent.Type
	(*URI)(nil),                             // 1: text.URI
	(*EditRequest)(nil),                     // 2: text.EditRequest
	(*EditResponse)(nil),                    // 3: text.EditResponse
	(*EditorEvent)(nil),                     // 4: text.EditorEvent
	(*EditorSubscribeRequest)(nil),          // 5: text.EditorSubscribeRequest
	(*SetLocationListRequest)(nil),          // 6: text.SetLocationListRequest
	(*SetLocationListResponse)(nil),         // 7: text.SetLocationListResponse
	(*EditCellRequest)(nil),                 // 8: text.EditCellRequest
	(*EditCellResponse)(nil),                // 9: text.EditCellResponse
	(*RawCellsRequest)(nil),                 // 10: text.RawCellsRequest
	(*RawCellsResponse)(nil),                // 11: text.RawCellsResponse
	(*MoveToLocationRequest)(nil),           // 12: text.MoveToLocationRequest
	(*MoveToLocationResponse)(nil),          // 13: text.MoveToLocationResponse
	(*RegisterCommandRequest)(nil),          // 14: text.RegisterCommandRequest
	(*CommandManual)(nil),                   // 15: text.CommandManual
	(*RegisterCommandResponse)(nil),         // 16: text.RegisterCommandResponse
	(*SetCursorRequest)(nil),                // 17: text.SetCursorRequest
	(*SetCursorResponse)(nil),               // 18: text.SetCursorResponse
	(*CursorRequest)(nil),                   // 19: text.CursorRequest
	(*CursorResponse)(nil),                  // 20: text.CursorResponse
	(*EditorRequest)(nil),                   // 21: text.EditorRequest
	(*EditorResponse)(nil),                  // 22: text.EditorResponse
	(*SetDefaultAttributesRequest)(nil),     // 23: text.SetDefaultAttributesRequest
	(*SetDefaultAttributesResponse)(nil),    // 24: text.SetDefaultAttributesResponse
	(*HandleCommandRequest)(nil),            // 25: text.HandleCommandRequest
	(*HandleCommandResponse)(nil),           // 26: text.HandleCommandResponse
	(*SetLocationListRequest_Location)(nil), // 27: text.SetLocationListRequest.Location
	(*rpc.CellRow)(nil),                     // 28: term.CellRow
	(*rpc.Coordinates)(nil),                 // 29: term.Coordinates
	(*rpc.Attributes)(nil),                  // 30: term.Attributes
}
var file_rpc_editor_proto_depIdxs = []int32{
	1,  // 0: text.EditRequest.resource_name:type_name -> text.URI
	28, // 1: text.EditRequest.buffer:type_name -> term.CellRow
	0,  // 2: text.EditorEvent.type:type_name -> text.EditorEvent.Type
	1,  // 3: text.EditorEvent.resource_name:type_name -> text.URI
	29, // 4: text.EditorEvent.start:type_name -> term.Coordinates
	29, // 5: text.EditorEvent.end:type_name -> term.Coordinates
	29, // 6: text.EditorEvent.from:type_name -> term.Coordinates
	29, // 7: text.EditorEvent.to:type_name -> term.Coordinates
	0,  // 8: text.EditorSubscribeRequest.type:type_name -> text.EditorEvent.Type
	1,  // 9: text.SetLocationListRequest.resource_name:type_name -> text.URI
	27, // 10: text.SetLocationListRequest.locations:type_name -> text.SetLocationListRequest.Location
	1,  // 11: text.EditCellRequest.resource_name:type_name -> text.URI
	29, // 12: text.EditCellRequest.start:type_name -> term.Coordinates
	29, // 13: text.EditCellRequest.end:type_name -> term.Coordinates
	29, // 14: text.EditCellResponse.from:type_name -> term.Coordinates
	29, // 15: text.EditCellResponse.to:type_name -> term.Coordinates
	1,  // 16: text.RawCellsRequest.resource_name:type_name -> text.URI
	28, // 17: text.RawCellsResponse.rows:type_name -> term.CellRow
	1,  // 18: text.MoveToLocationRequest.resource_name:type_name -> text.URI
	15, // 19: text.RegisterCommandRequest.command:type_name -> text.CommandManual
	15, // 20: text.CommandManual.commands:type_name -> text.CommandManual
	29, // 21: text.SetCursorRequest.pos:type_name -> term.Coordinates
	1,  // 22: text.SetCursorRequest.resource_name:type_name -> text.URI
	1,  // 23: text.CursorRequest.resource_name:type_name -> text.URI
	29, // 24: text.CursorResponse.pos:type_name -> term.Coordinates
	1,  // 25: text.EditorRequest.resource_name:type_name -> text.URI
	1,  // 26: text.SetDefaultAttributesRequest.resource_name:type_name -> text.URI
	30, // 27: text.SetDefaultAttributesRequest.attributes:type_name -> term.Attributes
	1,  // 28: text.HandleCommandRequest.resource_name:type_name -> text.URI
	29, // 29: text.HandleCommandRequest.cursor_content:type_name -> term.Coordinates
	29, // 30: text.HandleCommandRequest.cursor_window:type_name -> term.Coordinates
	29, // 31: text.SetLocationListRequest.Location.from:type_name -> term.Coordinates
	29, // 32: text.SetLocationListRequest.Location.to:type_name -> term.Coordinates
	30, // 33: text.SetLocationListRequest.Location.attr:type_name -> term.Attributes
	2,  // 34: text.Editor.Edit:input_type -> text.EditRequest
	14, // 35: text.Editor.Register:input_type -> text.RegisterCommandRequest
	17, // 36: text.Editor.SetCursor:input_type -> text.SetCursorRequest
	19, // 37: text.Editor.Cursor:input_type -> text.CursorRequest
	21, // 38: text.Editor.Editor:input_type -> text.EditorRequest
	6,  // 39: text.Editor.SetLocationList:input_type -> text.SetLocationListRequest
	12, // 40: text.Editor.MoveToNextLocation:input_type -> text.MoveToLocationRequest
	12, // 41: text.Editor.MoveToPrevLocation:input_type -> text.MoveToLocationRequest
	8,  // 42: text.Editor.EditCell:input_type -> text.EditCellRequest
	10, // 43: text.Editor.RawCells:input_type -> text.RawCellsRequest
	23, // 44: text.Editor.SetDefaultAttributes:input_type -> text.SetDefaultAttributesRequest
	5,  // 45: text.Editor.Subscribe:input_type -> text.EditorSubscribeRequest
	25, // 46: text.CommandHandler.HandleCommand:input_type -> text.HandleCommandRequest
	3,  // 47: text.Editor.Edit:output_type -> text.EditResponse
	16, // 48: text.Editor.Register:output_type -> text.RegisterCommandResponse
	18, // 49: text.Editor.SetCursor:output_type -> text.SetCursorResponse
	20, // 50: text.Editor.Cursor:output_type -> text.CursorResponse
	22, // 51: text.Editor.Editor:output_type -> text.EditorResponse
	7,  // 52: text.Editor.SetLocationList:output_type -> text.SetLocationListResponse
	13, // 53: text.Editor.MoveToNextLocation:output_type -> text.MoveToLocationResponse
	13, // 54: text.Editor.MoveToPrevLocation:output_type -> text.MoveToLocationResponse
	9,  // 55: text.Editor.EditCell:output_type -> text.EditCellResponse
	11, // 56: text.Editor.RawCells:output_type -> text.RawCellsResponse
	24, // 57: text.Editor.SetDefaultAttributes:output_type -> text.SetDefaultAttributesResponse
	4,  // 58: text.Editor.Subscribe:output_type -> text.EditorEvent
	26, // 59: text.CommandHandler.HandleCommand:output_type -> text.HandleCommandResponse
	47, // [47:60] is the sub-list for method output_type
	34, // [34:47] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_rpc_editor_proto_init() }
func file_rpc_editor_proto_init() {
	if File_rpc_editor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_editor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditorEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditorSubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLocationListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLocationListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditCellRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditCellResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawCellsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawCellsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveToLocationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveToLocationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterCommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandManual); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterCommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetCursorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetCursorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CursorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CursorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDefaultAttributesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDefaultAttributesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandleCommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandleCommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_editor_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLocationListRequest_Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_editor_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_rpc_editor_proto_goTypes,
		DependencyIndexes: file_rpc_editor_proto_depIdxs,
		EnumInfos:         file_rpc_editor_proto_enumTypes,
		MessageInfos:      file_rpc_editor_proto_msgTypes,
	}.Build()
	File_rpc_editor_proto = out.File
	file_rpc_editor_proto_rawDesc = nil
	file_rpc_editor_proto_goTypes = nil
	file_rpc_editor_proto_depIdxs = nil
}
