// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: rpc/editor.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EditorClient is the client API for Editor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EditorClient interface {
	Edit(ctx context.Context, in *EditRequest, opts ...grpc.CallOption) (*EditResponse, error)
	Register(ctx context.Context, in *RegisterCommandRequest, opts ...grpc.CallOption) (*RegisterCommandResponse, error)
	SetCursor(ctx context.Context, in *SetCursorRequest, opts ...grpc.CallOption) (*SetCursorResponse, error)
	Cursor(ctx context.Context, in *CursorRequest, opts ...grpc.CallOption) (*CursorResponse, error)
	Editor(ctx context.Context, in *EditorRequest, opts ...grpc.CallOption) (*EditorResponse, error)
	// locations
	SetLocationList(ctx context.Context, in *SetLocationListRequest, opts ...grpc.CallOption) (*SetLocationListResponse, error)
	MoveToNextLocation(ctx context.Context, in *MoveToLocationRequest, opts ...grpc.CallOption) (*MoveToLocationResponse, error)
	MoveToPrevLocation(ctx context.Context, in *MoveToLocationRequest, opts ...grpc.CallOption) (*MoveToLocationResponse, error)
	// Editor
	EditCell(ctx context.Context, in *EditCellRequest, opts ...grpc.CallOption) (*EditCellResponse, error)
	// View
	RawCells(ctx context.Context, in *RawCellsRequest, opts ...grpc.CallOption) (*RawCellsResponse, error)
	SetDefaultAttributes(ctx context.Context, in *SetDefaultAttributesRequest, opts ...grpc.CallOption) (*SetDefaultAttributesResponse, error)
	// streams
	Subscribe(ctx context.Context, opts ...grpc.CallOption) (Editor_SubscribeClient, error)
}

type editorClient struct {
	cc grpc.ClientConnInterface
}

func NewEditorClient(cc grpc.ClientConnInterface) EditorClient {
	return &editorClient{cc}
}

func (c *editorClient) Edit(ctx context.Context, in *EditRequest, opts ...grpc.CallOption) (*EditResponse, error) {
	out := new(EditResponse)
	err := c.cc.Invoke(ctx, "/text.Editor/Edit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editorClient) Register(ctx context.Context, in *RegisterCommandRequest, opts ...grpc.CallOption) (*RegisterCommandResponse, error) {
	out := new(RegisterCommandResponse)
	err := c.cc.Invoke(ctx, "/text.Editor/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editorClient) SetCursor(ctx context.Context, in *SetCursorRequest, opts ...grpc.CallOption) (*SetCursorResponse, error) {
	out := new(SetCursorResponse)
	err := c.cc.Invoke(ctx, "/text.Editor/SetCursor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editorClient) Cursor(ctx context.Context, in *CursorRequest, opts ...grpc.CallOption) (*CursorResponse, error) {
	out := new(CursorResponse)
	err := c.cc.Invoke(ctx, "/text.Editor/Cursor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editorClient) Editor(ctx context.Context, in *EditorRequest, opts ...grpc.CallOption) (*EditorResponse, error) {
	out := new(EditorResponse)
	err := c.cc.Invoke(ctx, "/text.Editor/Editor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editorClient) SetLocationList(ctx context.Context, in *SetLocationListRequest, opts ...grpc.CallOption) (*SetLocationListResponse, error) {
	out := new(SetLocationListResponse)
	err := c.cc.Invoke(ctx, "/text.Editor/SetLocationList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editorClient) MoveToNextLocation(ctx context.Context, in *MoveToLocationRequest, opts ...grpc.CallOption) (*MoveToLocationResponse, error) {
	out := new(MoveToLocationResponse)
	err := c.cc.Invoke(ctx, "/text.Editor/MoveToNextLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editorClient) MoveToPrevLocation(ctx context.Context, in *MoveToLocationRequest, opts ...grpc.CallOption) (*MoveToLocationResponse, error) {
	out := new(MoveToLocationResponse)
	err := c.cc.Invoke(ctx, "/text.Editor/MoveToPrevLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editorClient) EditCell(ctx context.Context, in *EditCellRequest, opts ...grpc.CallOption) (*EditCellResponse, error) {
	out := new(EditCellResponse)
	err := c.cc.Invoke(ctx, "/text.Editor/EditCell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editorClient) RawCells(ctx context.Context, in *RawCellsRequest, opts ...grpc.CallOption) (*RawCellsResponse, error) {
	out := new(RawCellsResponse)
	err := c.cc.Invoke(ctx, "/text.Editor/RawCells", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editorClient) SetDefaultAttributes(ctx context.Context, in *SetDefaultAttributesRequest, opts ...grpc.CallOption) (*SetDefaultAttributesResponse, error) {
	out := new(SetDefaultAttributesResponse)
	err := c.cc.Invoke(ctx, "/text.Editor/SetDefaultAttributes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editorClient) Subscribe(ctx context.Context, opts ...grpc.CallOption) (Editor_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &Editor_ServiceDesc.Streams[0], "/text.Editor/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &editorSubscribeClient{stream}
	return x, nil
}

type Editor_SubscribeClient interface {
	Send(*EditorSubscribeRequest) error
	Recv() (*EditorEvent, error)
	grpc.ClientStream
}

type editorSubscribeClient struct {
	grpc.ClientStream
}

func (x *editorSubscribeClient) Send(m *EditorSubscribeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *editorSubscribeClient) Recv() (*EditorEvent, error) {
	m := new(EditorEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EditorServer is the server API for Editor service.
// All implementations must embed UnimplementedEditorServer
// for forward compatibility
type EditorServer interface {
	Edit(context.Context, *EditRequest) (*EditResponse, error)
	Register(context.Context, *RegisterCommandRequest) (*RegisterCommandResponse, error)
	SetCursor(context.Context, *SetCursorRequest) (*SetCursorResponse, error)
	Cursor(context.Context, *CursorRequest) (*CursorResponse, error)
	Editor(context.Context, *EditorRequest) (*EditorResponse, error)
	// locations
	SetLocationList(context.Context, *SetLocationListRequest) (*SetLocationListResponse, error)
	MoveToNextLocation(context.Context, *MoveToLocationRequest) (*MoveToLocationResponse, error)
	MoveToPrevLocation(context.Context, *MoveToLocationRequest) (*MoveToLocationResponse, error)
	// Editor
	EditCell(context.Context, *EditCellRequest) (*EditCellResponse, error)
	// View
	RawCells(context.Context, *RawCellsRequest) (*RawCellsResponse, error)
	SetDefaultAttributes(context.Context, *SetDefaultAttributesRequest) (*SetDefaultAttributesResponse, error)
	// streams
	Subscribe(Editor_SubscribeServer) error
	mustEmbedUnimplementedEditorServer()
}

// UnimplementedEditorServer must be embedded to have forward compatible implementations.
type UnimplementedEditorServer struct {
}

func (UnimplementedEditorServer) Edit(context.Context, *EditRequest) (*EditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Edit not implemented")
}
func (UnimplementedEditorServer) Register(context.Context, *RegisterCommandRequest) (*RegisterCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedEditorServer) SetCursor(context.Context, *SetCursorRequest) (*SetCursorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCursor not implemented")
}
func (UnimplementedEditorServer) Cursor(context.Context, *CursorRequest) (*CursorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cursor not implemented")
}
func (UnimplementedEditorServer) Editor(context.Context, *EditorRequest) (*EditorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Editor not implemented")
}
func (UnimplementedEditorServer) SetLocationList(context.Context, *SetLocationListRequest) (*SetLocationListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLocationList not implemented")
}
func (UnimplementedEditorServer) MoveToNextLocation(context.Context, *MoveToLocationRequest) (*MoveToLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveToNextLocation not implemented")
}
func (UnimplementedEditorServer) MoveToPrevLocation(context.Context, *MoveToLocationRequest) (*MoveToLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveToPrevLocation not implemented")
}
func (UnimplementedEditorServer) EditCell(context.Context, *EditCellRequest) (*EditCellResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditCell not implemented")
}
func (UnimplementedEditorServer) RawCells(context.Context, *RawCellsRequest) (*RawCellsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawCells not implemented")
}
func (UnimplementedEditorServer) SetDefaultAttributes(context.Context, *SetDefaultAttributesRequest) (*SetDefaultAttributesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDefaultAttributes not implemented")
}
func (UnimplementedEditorServer) Subscribe(Editor_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedEditorServer) mustEmbedUnimplementedEditorServer() {}

// UnsafeEditorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EditorServer will
// result in compilation errors.
type UnsafeEditorServer interface {
	mustEmbedUnimplementedEditorServer()
}

func RegisterEditorServer(s grpc.ServiceRegistrar, srv EditorServer) {
	s.RegisterService(&Editor_ServiceDesc, srv)
}

func _Editor_Edit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditorServer).Edit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/text.Editor/Edit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditorServer).Edit(ctx, req.(*EditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Editor_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditorServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/text.Editor/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditorServer).Register(ctx, req.(*RegisterCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Editor_SetCursor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCursorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditorServer).SetCursor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/text.Editor/SetCursor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditorServer).SetCursor(ctx, req.(*SetCursorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Editor_Cursor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CursorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditorServer).Cursor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/text.Editor/Cursor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditorServer).Cursor(ctx, req.(*CursorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Editor_Editor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditorServer).Editor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/text.Editor/Editor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditorServer).Editor(ctx, req.(*EditorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Editor_SetLocationList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLocationListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditorServer).SetLocationList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/text.Editor/SetLocationList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditorServer).SetLocationList(ctx, req.(*SetLocationListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Editor_MoveToNextLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveToLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditorServer).MoveToNextLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/text.Editor/MoveToNextLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditorServer).MoveToNextLocation(ctx, req.(*MoveToLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Editor_MoveToPrevLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveToLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditorServer).MoveToPrevLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/text.Editor/MoveToPrevLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditorServer).MoveToPrevLocation(ctx, req.(*MoveToLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Editor_EditCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditorServer).EditCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/text.Editor/EditCell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditorServer).EditCell(ctx, req.(*EditCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Editor_RawCells_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawCellsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditorServer).RawCells(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/text.Editor/RawCells",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditorServer).RawCells(ctx, req.(*RawCellsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Editor_SetDefaultAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDefaultAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditorServer).SetDefaultAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/text.Editor/SetDefaultAttributes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditorServer).SetDefaultAttributes(ctx, req.(*SetDefaultAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Editor_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EditorServer).Subscribe(&editorSubscribeServer{stream})
}

type Editor_SubscribeServer interface {
	Send(*EditorEvent) error
	Recv() (*EditorSubscribeRequest, error)
	grpc.ServerStream
}

type editorSubscribeServer struct {
	grpc.ServerStream
}

func (x *editorSubscribeServer) Send(m *EditorEvent) error {
	return x.ServerStream.SendMsg(m)
}

func (x *editorSubscribeServer) Recv() (*EditorSubscribeRequest, error) {
	m := new(EditorSubscribeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Editor_ServiceDesc is the grpc.ServiceDesc for Editor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Editor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "text.Editor",
	HandlerType: (*EditorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Edit",
			Handler:    _Editor_Edit_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Editor_Register_Handler,
		},
		{
			MethodName: "SetCursor",
			Handler:    _Editor_SetCursor_Handler,
		},
		{
			MethodName: "Cursor",
			Handler:    _Editor_Cursor_Handler,
		},
		{
			MethodName: "Editor",
			Handler:    _Editor_Editor_Handler,
		},
		{
			MethodName: "SetLocationList",
			Handler:    _Editor_SetLocationList_Handler,
		},
		{
			MethodName: "MoveToNextLocation",
			Handler:    _Editor_MoveToNextLocation_Handler,
		},
		{
			MethodName: "MoveToPrevLocation",
			Handler:    _Editor_MoveToPrevLocation_Handler,
		},
		{
			MethodName: "EditCell",
			Handler:    _Editor_EditCell_Handler,
		},
		{
			MethodName: "RawCells",
			Handler:    _Editor_RawCells_Handler,
		},
		{
			MethodName: "SetDefaultAttributes",
			Handler:    _Editor_SetDefaultAttributes_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Editor_Subscribe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "rpc/editor.proto",
}

// CommandHandlerClient is the client API for CommandHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommandHandlerClient interface {
	HandleCommand(ctx context.Context, in *HandleCommandRequest, opts ...grpc.CallOption) (*HandleCommandResponse, error)
}

type commandHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandHandlerClient(cc grpc.ClientConnInterface) CommandHandlerClient {
	return &commandHandlerClient{cc}
}

func (c *commandHandlerClient) HandleCommand(ctx context.Context, in *HandleCommandRequest, opts ...grpc.CallOption) (*HandleCommandResponse, error) {
	out := new(HandleCommandResponse)
	err := c.cc.Invoke(ctx, "/text.CommandHandler/HandleCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandHandlerServer is the server API for CommandHandler service.
// All implementations must embed UnimplementedCommandHandlerServer
// for forward compatibility
type CommandHandlerServer interface {
	HandleCommand(context.Context, *HandleCommandRequest) (*HandleCommandResponse, error)
	mustEmbedUnimplementedCommandHandlerServer()
}

// UnimplementedCommandHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedCommandHandlerServer struct {
}

func (UnimplementedCommandHandlerServer) HandleCommand(context.Context, *HandleCommandRequest) (*HandleCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleCommand not implemented")
}
func (UnimplementedCommandHandlerServer) mustEmbedUnimplementedCommandHandlerServer() {}

// UnsafeCommandHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandHandlerServer will
// result in compilation errors.
type UnsafeCommandHandlerServer interface {
	mustEmbedUnimplementedCommandHandlerServer()
}

func RegisterCommandHandlerServer(s grpc.ServiceRegistrar, srv CommandHandlerServer) {
	s.RegisterService(&CommandHandler_ServiceDesc, srv)
}

func _CommandHandler_HandleCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandHandlerServer).HandleCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/text.CommandHandler/HandleCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandHandlerServer).HandleCommand(ctx, req.(*HandleCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommandHandler_ServiceDesc is the grpc.ServiceDesc for CommandHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommandHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "text.CommandHandler",
	HandlerType: (*CommandHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleCommand",
			Handler:    _CommandHandler_HandleCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/editor.proto",
}
