// Unstable Build LLC ("COMPANY") CONFIDENTIAL
//
// Unpublished Copyright (c) 2017-2024 Unstable Build, All Rights Reserved.
//
// NOTICE: All information contained herein is, and remains the property of COMPANY.
// The intellectual and technical concepts contained herein are proprietary to
// COMPANY and may be covered by U.S. and Foreign Patents, patents in process,
// and are protected by trade secret or copyright law. Dissemination of this information
// or reproduction of this material is strictly forbidden unless prior written permission
// is obtained from COMPANY. Access to the source code contained herein is hereby
// forbidden to anyone except current COMPANY employees, managers or contractors who
// have executed Confidentiality and Non-disclosure agreements explicitly covering such access.
//
// The copyright notice above does not evidence any actual or intended publication or
// disclosure of this source code, which includes information that is confidential and/or
// proprietary, and is a trade secret, of COMPANY. ANY REPRODUCTION, MODIFICATION,
// DISTRIBUTION, PUBLIC  PERFORMANCE, OR PUBLIC DISPLAY OF OR THROUGH USE OF THIS SOURCE CODE
// WITHOUT  THE EXPRESS WRITTEN CONSENT OF COMPANY IS STRICTLY PROHIBITED, AND IN
// VIOLATION OF APPLICABLE LAWS AND INTERNATIONAL TREATIES. THE RECEIPT OR POSSESSION OF
// THIS SOURCE CODE AND/OR RELATED INFORMATION DOES NOT CONVEY OR IMPLY ANY RIGHTS TO
// REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS, OR TO MANUFACTURE, USE, OR SELL
// ANYTHING THAT IT MAY DESCRIBE, IN WHOLE OR IN PART.

package handlerrpc

import (
	"context"
	"errors"
	"fmt"
	"io"
	"strings"
	"sync"
	"sync/atomic"

	log "github.com/sirupsen/logrus"
	"github.com/unstablebuild/blue/logging"
	grpc "google.golang.org/grpc"
	"unstable.build/go-tui"
	"unstable.build/go-tui/component"
	"unstable.build/go-tui/debug"
	"unstable.build/go-tui/term"
	"unstable.build/go-tui/term/termrpc"
)

// StreamMessage abstracts a generated protobuf message
// to enable generic usage of ServerStream and ClientStream.
//
// All the getters can be automatically generated by importing
// the following types and adding them as fields:
//
//	message MyMessage {
//	  handler.MessageType type = ?;
//	  handler.DrawStreamResponse draw = ?;
//	  handler.HandleStreamResponse handle = ?;
//	  handler.ManStreamResponse man = ?;
//	  handler.CloseStreamResponse close = ?;
//	  handler.CursorStreamResponse cursor = ?;
//	  handler.SelectionStreamResponse selection = ?;
//	  handler.DimensionsStreamResponse dimensions = ?;
//	  handler.ResizeStreamResponse resize = ?;
//
// The setters must be added manually.
type StreamMessage interface {
	ProtoMessage()

	GetType() MessageType
	GetDraw() *DrawStreamResponse
	GetHandle() *HandleStreamResponse
	GetMan() *ManStreamResponse
	GetClose() *CloseStreamResponse
	GetCursor() *CursorStreamResponse
	GetSelection() *SelectionStreamResponse
	GetDimensions() *DimensionsStreamResponse

	SetDraw(*DrawStreamResponse)
	SetHandle(*HandleStreamResponse)
	SetMan(*ManStreamResponse)
	SetClose(*CloseStreamResponse)
	SetCursor(*CursorStreamResponse)
	SetSelection(*SelectionStreamResponse)
	SetDimensions(*DimensionsStreamResponse)
}

// ClientStream implements a tui.Handler (+handler.Floating) server over
// a grpc.ServerStream.
type ClientStream[T StreamMessage] struct {
	ctx       context.Context
	cancel    func()
	stream    grpc.ServerStream
	closeChan chan error
	publisher func(ev term.Event) error
	exit      atomic.Bool
	closed    atomic.Bool
	newT      func() T

	respPending    atomic.Bool
	respPendingMsg *ServerMessage

	// these are all cached when client calls Draw
	mu             sync.Mutex
	contextPayload string
	height         int
	width          int
	state          asyncState
	cursor         *CursorStreamResponse
	selection      *SelectionStreamResponse
	man            *ManStreamResponse
	dimensions     *DimensionsStreamResponse

	req struct {
		height, width int
		ctx           context.Context
	}
	resp struct {
		*DrawStreamResponse
		ctx           context.Context
		height, width int
	}
}

// NewClientStream allocates storage for a new ClientStream and initializes it
// with the given grpc.ServerStream and type parameter constructor.
func NewClientStream[T StreamMessage](
	ctx context.Context, srv grpc.ServerStream, newT func() T,
	publisher func(ev term.Event) error,
) *ClientStream[T] {
	ctx, cancel := context.WithCancel(ctx)
	s := &ClientStream[T]{
		ctx:       ctx,
		cancel:    cancel,
		stream:    srv,
		closeChan: make(chan error),
		newT:      newT,
		publisher: publisher,
	}
	s.contextPayload = makeContextPayload(s)
	s.resp.ctx = context.Background()
	return s
}

// ScheduleResponse schedules the install response to be sent
// on the next tui.Handler method call to this ClientStream.
//
// This method must only be called once.
func (s *ClientStream[T]) ScheduleResponse(resp *ServerMessage) {
	if !s.respPending.CompareAndSwap(false, true) {
		panic("cannot call ScheduleResponse twice")
	}
	s.respPendingMsg = resp
}

// ReceiveMessages blocks until all messages have been received and the stream
// is ready to be closed.
func (s *ClientStream[T]) ReceiveMessages() (ret error) {
	defer func() {
		s.log(log.DebugLevel, "receive messages returned: error: %v", ret)
	}()

	go debug.CapturePanicReport(func() {
		s.log(log.TraceLevel, "streaming messages")
		s.closeStream(s.receiveMessages())
	})

	select {
	case err := <-s.closeChan:
		ret = err
		return
	case <-s.ctx.Done():
		ret = fmt.Errorf("context is done: %w", s.ctx.Err())
		return
	}
}

// Handle satisfies Handler.
func (s *ClientStream[T]) Handle(ev term.Event) (exit, handled bool) {
	if s.exit.Load() {
		exit = true
		return
	}
	if s.closed.Load() {
		return
	}
	pending := s.respPending.CompareAndSwap(true, false)
	if pending {
		if err := s.stream.SendMsg(s.respPendingMsg); err != nil {
			s.closeStream(fmt.Errorf("send install response: %w", err))
			return
		}
	}
	var tev termrpc.Event
	err := tev.FromModel(ev)
	if err != nil {
		s.closeStream(fmt.Errorf("convert ev to proto ev: %w", err))
		return
	}
	req := HandleStreamRequest{Event: &tev}
	sendMsg := ServerMessage{Type: MessageType_Handle, Handle: &req}
	if err := s.stream.SendMsg(&sendMsg); err != nil {
		s.closeStream(fmt.Errorf("send handle message: %w", err))
		return
	}

	// it's important for Handle to remain asynchronous:
	// it allows for extensions to call API and avoid deadlocks
	// due to extensions needing the global lock to be open to call the host
	// at the same time the host is locked waiting for Handle to return.

	handled = true
	return
}

// Cursor satisfies Handler. This method returns the last cursor collected by Draw.
func (s *ClientStream[T]) Cursor() (c term.Coordinates, cs term.CursorStyle, show bool) {
	s.mu.Lock()
	defer s.mu.Unlock()

	cursor := s.cursor
	show = cursor.GetShow()
	if !show {
		return
	}
	cs = term.CursorStyle(cursor.GetStyle())
	c.X = int(cursor.GetPosition().GetX())
	c.Y = int(cursor.GetPosition().GetY())
	return
}

// Selection satisfies Handler. This method returns the last selection collected by Draw.
func (s *ClientStream[T]) Selection() (string, bool) {
	s.mu.Lock()
	defer s.mu.Unlock()

	selection := s.selection
	return selection.GetText(), selection.GetOk()
}

// Man satisfies Handler. This method is not implemented
// to avoid triggering unimplemented panics.
func (s *ClientStream[T]) Man() tui.Manual {
	/* man := s.man.Load().(*ManStreamResponse)
	tuiMan, err := man.GetMan().ToModel()
	if err != nil {
		s.closeStream(fmt.Errorf("man to model: %w", err))
		return tui.Manual{}
	}
	return tuiMan
	*/
	panic("unimplemented")
}

// Resize satisfies Handler.
func (s *ClientStream[T]) Resize(width, height int) {
	s.mu.Lock()
	defer s.mu.Unlock()

	// store in any case for error displaying
	s.height = height
	s.width = width

	if s.closed.Load() {
		return
	}

	pending := s.respPending.CompareAndSwap(true, false)
	if pending {
		if err := s.stream.SendMsg(s.respPendingMsg); err != nil {
			s.closeStream(fmt.Errorf("send install response: %w", err))
			return
		}
	}

	var req ResizeStreamRequest
	req.Width = int32(width)
	req.Height = int32(height)
	sendMsg := ServerMessage{Type: MessageType_Resize, Resize: &req}
	err := s.stream.SendMsg(&sendMsg)
	if err != nil {
		err := fmt.Errorf("send resize message: %w", err)
		s.closeStream(err)
		return
	}
}

// Dimensions satisfies Handler. This method returns the last
// dimensions collected by Draw.
func (s *ClientStream[T]) Dimensions() (width int, height int) {
	s.mu.Lock()
	defer s.mu.Unlock()

	dim := s.dimensions
	width = int(dim.GetWidth())
	height = int(dim.GetHeight())
	return
}

// Draw satisfies Handler.
func (s *ClientStream[T]) Draw(w term.Writer) {
	pending := s.respPending.CompareAndSwap(true, false)
	if pending {
		if err := s.stream.SendMsg(s.respPendingMsg); err != nil {
			s.closeStream(fmt.Errorf("send install response: %w", err))
			return
		}
	}
	s.mu.Lock()
	defer s.mu.Unlock()

	ctx := w.Context()
	iterationID, reqIsTick := tui.IterationFromContext(ctx)

	switch s.state {
	case stateAsyncIdle:
		readySameDimensions := s.width == s.resp.width &&
			s.height == s.resp.height
		respIterationID, respIsTick := tui.IterationFromContext(s.resp.ctx)
		olderIterationID := respIsTick && iterationID <= respIterationID
		reqIsSameIterationID := (reqIsTick && olderIterationID)
		selfInterrupt := !reqIsTick && !respIsTick && s.contextPayloadIsSelf(ctx)

		if readySameDimensions && (reqIsSameIterationID || selfInterrupt ||
			s.contextPayloadIsOtherAsyncClient(ctx)) {
			s.drawReady(w)
		} else if s.scheduleDrawRequest(ctx, reqIsTick) {
			s.drawPending(w)
		} else {
			s.log(log.TraceLevel, "could not schedule draw request")
			s.drawError(w)
		}
	case stateAsyncPending:
		pendingRespSameDimensions := s.width == s.req.width &&
			s.height == s.req.height
		pendingResponseIterationID, pendingResponseIsTick := tui.IterationFromContext(s.req.ctx)
		olderIterationID := pendingResponseIsTick && iterationID <= pendingResponseIterationID
		pendingResponseIsSameIterationID := (reqIsTick && olderIterationID)

		if pendingRespSameDimensions && (pendingResponseIsSameIterationID ||
			s.contextPayloadIsOtherAsyncClient(ctx)) {
			s.drawPending(w)
		} else if s.scheduleDrawRequest(ctx, reqIsTick) {
			s.drawPending(w)
		} else {
			s.log(log.TraceLevel, "could not schedule draw request")
			s.drawError(w)
		}
	case stateAsyncCircuitBreak:
		s.log(log.TraceLevel, "received draw but state is circuit break")
		s.drawError(w)
	default:
		panic("unknown state")
	}
}

// Close satisfies Handler.
func (s *ClientStream[T]) Close() error {
	if s.closed.Load() {
		return nil
	}
	s.log(log.TraceLevel, "Close")
	var req CloseStreamRequest
	msg := ServerMessage{Type: MessageType_Close, Close: &req}
	err := s.stream.SendMsg(&msg)
	if err != nil {
		err = fmt.Errorf("send close message: %w", err)
		s.closeStream(err)
		return err
	}

	return nil
}

const (
	smtgWrongCopy = `

          ___
         /___/\_               
        _\   \/_/\__           
      __\       \/_/\          
      \   __    __ \ \         
     __\  \_\   \_\ \ \   __   
    /_/\\   __   __  \ \_/_/\  
    \_\/_\__\/\__\/\__\/_\_\/  
       \_\/_/\       /_\_\/    
          \_\/       \_\/      
    

Uh, Houston, we've had a problem
`
)

var _ tui.Handler = (*ClientStream[StreamMessage])(nil)

type asyncState uint8

const (
	stateAsyncIdle asyncState = iota
	stateAsyncPending
	stateAsyncCircuitBreak
)

func (s *ClientStream[T]) scheduleDrawRequest(ctx context.Context, reqIsTick bool) bool {
	// make sure that all requests that we schedule interrupts for have
	// either an iteration ID or a payload that we can recognize.
	if !reqIsTick {
		ctx = s.contextWithSelfPayload(ctx)
	}

	s.state = stateAsyncPending
	s.req.width = s.width
	s.req.height = s.height
	s.req.ctx = ctx

	{
		var req CursorStreamRequest
		sendMsg := ServerMessage{Type: MessageType_Cursor, Cursor: &req}
		err := s.stream.SendMsg(&sendMsg)
		if err != nil {
			err := fmt.Errorf("send cursor message: %w", err)
			s.closeStream(err)
			return false
		}
	}
	{
		var req SelectionStreamRequest
		sendMsg := ServerMessage{Type: MessageType_Selection, Selection: &req}
		err := s.stream.SendMsg(&sendMsg)
		if err != nil {
			err := fmt.Errorf("send selection message: %w", err)
			s.closeStream(err)
			return false
		}
	}
	{
		var req DimensionsStreamRequest
		sendMsg := ServerMessage{Type: MessageType_Dimensions, Dimensions: &req}
		err := s.stream.SendMsg(&sendMsg)
		if err != nil {
			err := fmt.Errorf("send dimensions message: %w", err)
			s.closeStream(err)
			return false
		}
	}

	// finally send a draw request, which will trigger the final interrupt
	{
		var req DrawStreamRequest
		sendMsg := ServerMessage{Type: MessageType_Draw, Draw: &req}
		err := s.stream.SendMsg(&sendMsg)
		if err != nil {
			err := fmt.Errorf("send draw message: %w", err)
			s.closeStream(err)
			return false
		}
	}

	return true
}

func (s *ClientStream[T]) processDraw(resp *DrawStreamResponse) {
	s.mu.Lock()
	defer s.mu.Unlock()

	payload, _ := term.PayloadFromContext(s.req.ctx)

	//nolint:errcheck
	defer s.publisher(term.Event{Type: term.EventInterrupt, Raw: payload})

	s.resp.DrawStreamResponse = resp

	s.resp.ctx = s.req.ctx
	s.resp.height = int(s.req.height)
	s.resp.width = int(s.req.width)

	s.state = stateAsyncIdle
}

func (s *ClientStream[T]) receiveMessages() (ret error) {
	defer func() {
		s.cancel()
		if ret != nil {
			s.log(log.TraceLevel, "done receiving messages: error: %v", ret)
		}
		s.mu.Lock()
		defer s.mu.Unlock()
		s.state = stateAsyncCircuitBreak
	}()

	for {
		recvMsg := s.newT()
		if err := s.stream.RecvMsg(recvMsg); err != nil {
			ret = fmt.Errorf("stream receive message: %w", err)
			return
		}

		switch recvMsg.GetType() {
		case MessageType_Draw:
			draw := recvMsg.GetDraw()
			if draw == nil {
				ret = fmt.Errorf("receive draw message: missing data")
			}
			s.processDraw(draw)
		case MessageType_Man:
			man := recvMsg.GetMan()
			if man == nil || man.GetMan() == nil {
				ret = fmt.Errorf("receive man message: missing data")
				return
			}
			s.mu.Lock()
			s.man = man
			s.mu.Unlock()
		case MessageType_Cursor:
			cursor := recvMsg.GetCursor()
			if cursor == nil {
				ret = fmt.Errorf("receive cursor message: missing data")
				return
			}
			s.mu.Lock()
			s.cursor = cursor
			s.mu.Unlock()
		case MessageType_Selection:
			selection := recvMsg.GetSelection()
			if selection == nil {
				ret = fmt.Errorf("receive selection message: missing data")
				return
			}
			s.mu.Lock()
			s.selection = selection
			s.mu.Unlock()
		case MessageType_Dimensions:
			dimensions := recvMsg.GetDimensions()
			if dimensions == nil {
				ret = fmt.Errorf("receive dimensions message: missing data")
				return
			}
			s.mu.Lock()
			s.dimensions = dimensions
			s.mu.Unlock()
		case MessageType_Handle:
			handle := recvMsg.GetHandle()
			// GetHandled is ignored; Handle always returns true
			exit := handle.GetQuit()
			if exit && s.closed.CompareAndSwap(false, true) {
				// shortcircuit calling Close so there aren't unintended
				// side effects from returning exit=false in the call that
				// originated this response. Publishing term.EventNone,
				// might not be enough, if focus changed.
				var req CloseStreamRequest
				msg := ServerMessage{Type: MessageType_Close, Close: &req}
				ret = s.stream.SendMsg(&msg)
			}
		case MessageType_Resize:
			/* nothing to do*/
		case MessageType_Close:
			s.log(log.TraceLevel, "received close message")
			return
		default:
			/* case MessageType_Request, MessageType_Response: */
			ret = fmt.Errorf("received extraneous message type: %d", recvMsg.GetType())
			return
		}
	}
}

func (s *ClientStream[T]) closeStream(err error) {
	if !s.closed.CompareAndSwap(false, true) {
		s.log(log.TraceLevel, "close stream called multiple times")
		return
	}
	if err != nil &&
		(errors.Is(err, io.EOF) || strings.Contains(err.Error(), "context canceled")) {
		err = nil
	}
	if err != nil {
		s.log(log.ErrorLevel, "closing stream due to error: %v", err)
	}
	// this forces ReceiveMessages to return, which in turn trickles server
	// to close stream, and receiveMessages RecvMsg returns with error.
	select {
	case s.closeChan <- err:
	default:
	}
}

func (s *ClientStream[T]) drawError(w term.Writer) {
	comp := component.NewStringWithConfig(smtgWrongCopy,
		component.StringConfig{Alignment: component.SpanAlignmentCentered})
	comp.Resize(s.width, s.height)
	comp.Draw(w)
}

func (s *ClientStream[T]) drawPending(w term.Writer) {
	if s.width == s.resp.width && s.height == s.resp.height {
		s.drawReady(w)
	} else {
		loading := component.NewStringWithConfig("LOADING",
			component.StringConfig{Alignment: component.SpanAlignmentCentered})
		loading.Resize(s.width, s.height)
		loading.Draw(w)
	}
}

func (s *ClientStream[T]) drawReady(w term.Writer) {
	doDraw(w, s.resp.DrawStreamResponse.GetRows())
}

func (s *ClientStream[T]) log(level log.Level, msg string, args ...interface{}) {
	if !log.IsLevelEnabled(level) {
		return
	}
	log.WithFields(log.Fields{
		logging.KeyClass: "handlerrpc.ClientStream",
		"instance":       fmt.Sprintf("%p", s),
	}).Logf(level, msg, args...)
}

func (s *ClientStream[T]) contextPayloadIsSelf(ctx context.Context) bool {
	payload, ok := term.PayloadFromContext(ctx)
	return ok && s.contextPayload == string(payload)
}

func (s *ClientStream[T]) contextPayloadIsOtherAsyncClient(ctx context.Context) bool {
	payload, ok := term.PayloadFromContext(ctx)
	return ok && strings.HasPrefix(string(payload), ctxPayloadPrefix)
}

const ctxPayloadPrefix = "AsyncClient"

func (s *ClientStream[T]) contextWithSelfPayload(ctx context.Context) context.Context {
	return term.ContextWithPayload(ctx, []byte(s.contextPayload))
}

func makeContextPayload[T StreamMessage](s *ClientStream[T]) string {
	return fmt.Sprintf("%s:%p", ctxPayloadPrefix, s)
}

func doDraw(w term.Writer, rows []*termrpc.CellRow) {
	for y, row := range rows {
		for x, c := range row.Cells {
			cell := c.ToModel()
			w.SetCell(term.Coordinates{X: x, Y: y}, cell)
		}
	}
}
