// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: browser.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Orientation int32

const (
	Orientation_Default Orientation = 0
	Orientation_Top     Orientation = 1
	Orientation_Bottom  Orientation = 2
	Orientation_Left    Orientation = 3
	Orientation_Right   Orientation = 4
)

// Enum value maps for Orientation.
var (
	Orientation_name = map[int32]string{
		0: "Default",
		1: "Top",
		2: "Bottom",
		3: "Left",
		4: "Right",
	}
	Orientation_value = map[string]int32{
		"Default": 0,
		"Top":     1,
		"Bottom":  2,
		"Left":    3,
		"Right":   4,
	}
)

func (x Orientation) Enum() *Orientation {
	p := new(Orientation)
	*p = x
	return p
}

func (x Orientation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Orientation) Descriptor() protoreflect.EnumDescriptor {
	return file_browser_proto_enumTypes[0].Descriptor()
}

func (Orientation) Type() protoreflect.EnumType {
	return &file_browser_proto_enumTypes[0]
}

func (x Orientation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Orientation.Descriptor instead.
func (Orientation) EnumDescriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{0}
}

type OpenResourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource string `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *OpenResourceRequest) Reset() {
	*x = OpenResourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResourceRequest) ProtoMessage() {}

func (x *OpenResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResourceRequest.ProtoReflect.Descriptor instead.
func (*OpenResourceRequest) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{0}
}

func (x *OpenResourceRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type OpenResourceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HandlerId uint64 `protobuf:"varint,1,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
}

func (x *OpenResourceResponse) Reset() {
	*x = OpenResourceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResourceResponse) ProtoMessage() {}

func (x *OpenResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResourceResponse.ProtoReflect.Descriptor instead.
func (*OpenResourceResponse) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{1}
}

func (x *OpenResourceResponse) GetHandlerId() uint64 {
	if x != nil {
		return x.HandlerId
	}
	return 0
}

type SetMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SetMessageRequest) Reset() {
	*x = SetMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMessageRequest) ProtoMessage() {}

func (x *SetMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMessageRequest.ProtoReflect.Descriptor instead.
func (*SetMessageRequest) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{2}
}

func (x *SetMessageRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SetMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetMessageResponse) Reset() {
	*x = SetMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMessageResponse) ProtoMessage() {}

func (x *SetMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMessageResponse.ProtoReflect.Descriptor instead.
func (*SetMessageResponse) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{3}
}

type Mapping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From *Event `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To   *Event `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *Mapping) Reset() {
	*x = Mapping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mapping) ProtoMessage() {}

func (x *Mapping) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mapping.ProtoReflect.Descriptor instead.
func (*Mapping) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{4}
}

func (x *Mapping) GetFrom() *Event {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Mapping) GetTo() *Event {
	if x != nil {
		return x.To
	}
	return nil
}

type SplitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HandlerId   uint64      `protobuf:"varint,1,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
	Orientation Orientation `protobuf:"varint,2,opt,name=orientation,proto3,enum=proto.Orientation" json:"orientation,omitempty"`
}

func (x *SplitRequest) Reset() {
	*x = SplitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SplitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitRequest) ProtoMessage() {}

func (x *SplitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitRequest.ProtoReflect.Descriptor instead.
func (*SplitRequest) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{5}
}

func (x *SplitRequest) GetHandlerId() uint64 {
	if x != nil {
		return x.HandlerId
	}
	return 0
}

func (x *SplitRequest) GetOrientation() Orientation {
	if x != nil {
		return x.Orientation
	}
	return Orientation_Default
}

type SplitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WindowId uint64 `protobuf:"varint,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
}

func (x *SplitResponse) Reset() {
	*x = SplitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SplitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitResponse) ProtoMessage() {}

func (x *SplitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitResponse.ProtoReflect.Descriptor instead.
func (*SplitResponse) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{6}
}

func (x *SplitResponse) GetWindowId() uint64 {
	if x != nil {
		return x.WindowId
	}
	return 0
}

type BarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HandlerId   uint64      `protobuf:"varint,1,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
	Orientation Orientation `protobuf:"varint,2,opt,name=orientation,proto3,enum=proto.Orientation" json:"orientation,omitempty"`
}

func (x *BarRequest) Reset() {
	*x = BarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarRequest) ProtoMessage() {}

func (x *BarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarRequest.ProtoReflect.Descriptor instead.
func (*BarRequest) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{7}
}

func (x *BarRequest) GetHandlerId() uint64 {
	if x != nil {
		return x.HandlerId
	}
	return 0
}

func (x *BarRequest) GetOrientation() Orientation {
	if x != nil {
		return x.Orientation
	}
	return Orientation_Default
}

type BarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BarResponse) Reset() {
	*x = BarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarResponse) ProtoMessage() {}

func (x *BarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarResponse.ProtoReflect.Descriptor instead.
func (*BarResponse) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{8}
}

type FloatingWindowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HandlerId uint64       `protobuf:"varint,1,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
	At        *Coordinates `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	Height    int32        `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Width     int32        `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
}

func (x *FloatingWindowRequest) Reset() {
	*x = FloatingWindowRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FloatingWindowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatingWindowRequest) ProtoMessage() {}

func (x *FloatingWindowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatingWindowRequest.ProtoReflect.Descriptor instead.
func (*FloatingWindowRequest) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{9}
}

func (x *FloatingWindowRequest) GetHandlerId() uint64 {
	if x != nil {
		return x.HandlerId
	}
	return 0
}

func (x *FloatingWindowRequest) GetAt() *Coordinates {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *FloatingWindowRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *FloatingWindowRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

type FloatingWindowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WindowId uint64 `protobuf:"varint,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
}

func (x *FloatingWindowResponse) Reset() {
	*x = FloatingWindowResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FloatingWindowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatingWindowResponse) ProtoMessage() {}

func (x *FloatingWindowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatingWindowResponse.ProtoReflect.Descriptor instead.
func (*FloatingWindowResponse) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{10}
}

func (x *FloatingWindowResponse) GetWindowId() uint64 {
	if x != nil {
		return x.WindowId
	}
	return 0
}

type TabRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HandlerId    uint64 `protobuf:"varint,1,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
	ResourceId   string `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceName string `protobuf:"bytes,3,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
}

func (x *TabRequest) Reset() {
	*x = TabRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TabRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabRequest) ProtoMessage() {}

func (x *TabRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabRequest.ProtoReflect.Descriptor instead.
func (*TabRequest) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{11}
}

func (x *TabRequest) GetHandlerId() uint64 {
	if x != nil {
		return x.HandlerId
	}
	return 0
}

func (x *TabRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *TabRequest) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

type TabResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TabHandlerId uint64 `protobuf:"varint,1,opt,name=tab_handler_id,json=tabHandlerId,proto3" json:"tab_handler_id,omitempty"`
}

func (x *TabResponse) Reset() {
	*x = TabResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TabResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabResponse) ProtoMessage() {}

func (x *TabResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabResponse.ProtoReflect.Descriptor instead.
func (*TabResponse) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{12}
}

func (x *TabResponse) GetTabHandlerId() uint64 {
	if x != nil {
		return x.TabHandlerId
	}
	return 0
}

type FocusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FocusRequest) Reset() {
	*x = FocusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FocusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FocusRequest) ProtoMessage() {}

func (x *FocusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FocusRequest.ProtoReflect.Descriptor instead.
func (*FocusRequest) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{13}
}

type FocusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WindowId uint64 `protobuf:"varint,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
}

func (x *FocusResponse) Reset() {
	*x = FocusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FocusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FocusResponse) ProtoMessage() {}

func (x *FocusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FocusResponse.ProtoReflect.Descriptor instead.
func (*FocusResponse) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{14}
}

func (x *FocusResponse) GetWindowId() uint64 {
	if x != nil {
		return x.WindowId
	}
	return 0
}

type PublishRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ev *Event `protobuf:"bytes,1,opt,name=ev,proto3" json:"ev,omitempty"`
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{15}
}

func (x *PublishRequest) GetEv() *Event {
	if x != nil {
		return x.Ev
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{16}
}

type WindowCloseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WindowCloseRequest) Reset() {
	*x = WindowCloseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WindowCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowCloseRequest) ProtoMessage() {}

func (x *WindowCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowCloseRequest.ProtoReflect.Descriptor instead.
func (*WindowCloseRequest) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{17}
}

type WindowCloseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WindowCloseResponse) Reset() {
	*x = WindowCloseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WindowCloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowCloseResponse) ProtoMessage() {}

func (x *WindowCloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowCloseResponse.ProtoReflect.Descriptor instead.
func (*WindowCloseResponse) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{18}
}

type WindowSetContentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HandlerId uint64 `protobuf:"varint,1,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
}

func (x *WindowSetContentRequest) Reset() {
	*x = WindowSetContentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WindowSetContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowSetContentRequest) ProtoMessage() {}

func (x *WindowSetContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowSetContentRequest.ProtoReflect.Descriptor instead.
func (*WindowSetContentRequest) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{19}
}

func (x *WindowSetContentRequest) GetHandlerId() uint64 {
	if x != nil {
		return x.HandlerId
	}
	return 0
}

type WindowSetContentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WindowSetContentResponse) Reset() {
	*x = WindowSetContentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WindowSetContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowSetContentResponse) ProtoMessage() {}

func (x *WindowSetContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowSetContentResponse.ProtoReflect.Descriptor instead.
func (*WindowSetContentResponse) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{20}
}

type WindowContentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WindowContentRequest) Reset() {
	*x = WindowContentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WindowContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowContentRequest) ProtoMessage() {}

func (x *WindowContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowContentRequest.ProtoReflect.Descriptor instead.
func (*WindowContentRequest) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{21}
}

type WindowContentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HandlerId uint64 `protobuf:"varint,1,opt,name=handler_id,json=handlerId,proto3" json:"handler_id,omitempty"`
}

func (x *WindowContentResponse) Reset() {
	*x = WindowContentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WindowContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowContentResponse) ProtoMessage() {}

func (x *WindowContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowContentResponse.ProtoReflect.Descriptor instead.
func (*WindowContentResponse) Descriptor() ([]byte, []int) {
	return file_browser_proto_rawDescGZIP(), []int{22}
}

func (x *WindowContentResponse) GetHandlerId() uint64 {
	if x != nil {
		return x.HandlerId
	}
	return 0
}

var File_browser_proto protoreflect.FileDescriptor

var file_browser_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x72, 0x6f, 0x77, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x74, 0x65, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x09, 0x74, 0x75, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a,
	0x13, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x22, 0x35, 0x0a, 0x14, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x68, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x22, 0x25, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x14,
	0x0a, 0x12, 0x53, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x49, 0x0a, 0x07, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12,
	0x20, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x66, 0x72, 0x6f,
	0x6d, 0x12, 0x1c, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x02, 0x74, 0x6f, 0x22,
	0x63, 0x0a, 0x0c, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x12, 0x34,
	0x0a, 0x0b, 0x6f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x72, 0x69, 0x65,
	0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2c, 0x0a, 0x0d, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77,
	0x49, 0x64, 0x22, 0x61, 0x0a, 0x0a, 0x42, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x34, 0x0a, 0x0b, 0x6f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x72, 0x69,
	0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x65, 0x6e, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x0d, 0x0a, 0x0b, 0x42, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x88, 0x01, 0x0a, 0x15, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a,
	0x02, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x02, 0x61,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64,
	0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x22,
	0x35, 0x0a, 0x16, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x57, 0x69, 0x6e, 0x64, 0x6f,
	0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x69, 0x6e,
	0x64, 0x6f, 0x77, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x77, 0x69,
	0x6e, 0x64, 0x6f, 0x77, 0x49, 0x64, 0x22, 0x71, 0x0a, 0x0a, 0x54, 0x61, 0x62, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x33, 0x0a, 0x0b, 0x54, 0x61, 0x62,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x74, 0x61, 0x62, 0x5f,
	0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0c, 0x74, 0x61, 0x62, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x22, 0x0e,
	0x0a, 0x0c, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2c,
	0x0a, 0x0d, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x0e,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x02, 0x65, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x02, 0x65, 0x76, 0x22, 0x11, 0x0a, 0x0f,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x14, 0x0a, 0x12, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x38, 0x0a, 0x17,
	0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x68, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x22, 0x1a, 0x0a, 0x18, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77,
	0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x36, 0x0a, 0x15, 0x57, 0x69,
	0x6e, 0x64, 0x6f, 0x77, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72,
	0x49, 0x64, 0x2a, 0x44, 0x0a, 0x0b, 0x4f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x10, 0x00, 0x12, 0x07,
	0x0a, 0x03, 0x54, 0x6f, 0x70, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x6f, 0x74, 0x74, 0x6f,
	0x6d, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x65, 0x66, 0x74, 0x10, 0x03, 0x12, 0x09, 0x0a,
	0x05, 0x52, 0x69, 0x67, 0x68, 0x74, 0x10, 0x04, 0x32, 0x51, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x65, 0x72, 0x12, 0x3f, 0x0a, 0x04, 0x4f, 0x70,
	0x65, 0x6e, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x4e, 0x0a, 0x09, 0x4d,
	0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x12, 0x41, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x4a, 0x0a, 0x0e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x12, 0x38, 0x0a,
	0x07, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x9c, 0x02, 0x0a, 0x0d, 0x57, 0x69, 0x6e, 0x64,
	0x6f, 0x77, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x32, 0x0a, 0x05, 0x46, 0x6f, 0x63,
	0x75, 0x73, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x6f, 0x63, 0x75, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x46, 0x6f, 0x63, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a,
	0x05, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x70, 0x6c, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2c, 0x0a, 0x03, 0x42, 0x61, 0x72, 0x12, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x42, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x47, 0x0a, 0x08, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x57, 0x69, 0x6e, 0x64,
	0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x03, 0x54, 0x61, 0x62, 0x12,
	0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x61, 0x62, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xdd, 0x01, 0x0a, 0x06, 0x57, 0x69, 0x6e, 0x64, 0x6f,
	0x77, 0x12, 0x4d, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x53, 0x65,
	0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x53, 0x65,
	0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x44, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x05, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x12,
	0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x43, 0x6c,
	0x6f, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x72, 0x6e, 0x65, 0x73, 0x74, 0x72, 0x63, 0x2f, 0x67, 0x6f,
	0x2d, 0x74, 0x75, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_browser_proto_rawDescOnce sync.Once
	file_browser_proto_rawDescData = file_browser_proto_rawDesc
)

func file_browser_proto_rawDescGZIP() []byte {
	file_browser_proto_rawDescOnce.Do(func() {
		file_browser_proto_rawDescData = protoimpl.X.CompressGZIP(file_browser_proto_rawDescData)
	})
	return file_browser_proto_rawDescData
}

var file_browser_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_browser_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_browser_proto_goTypes = []interface{}{
	(Orientation)(0),                 // 0: proto.Orientation
	(*OpenResourceRequest)(nil),      // 1: proto.OpenResourceRequest
	(*OpenResourceResponse)(nil),     // 2: proto.OpenResourceResponse
	(*SetMessageRequest)(nil),        // 3: proto.SetMessageRequest
	(*SetMessageResponse)(nil),       // 4: proto.SetMessageResponse
	(*Mapping)(nil),                  // 5: proto.Mapping
	(*SplitRequest)(nil),             // 6: proto.SplitRequest
	(*SplitResponse)(nil),            // 7: proto.SplitResponse
	(*BarRequest)(nil),               // 8: proto.BarRequest
	(*BarResponse)(nil),              // 9: proto.BarResponse
	(*FloatingWindowRequest)(nil),    // 10: proto.FloatingWindowRequest
	(*FloatingWindowResponse)(nil),   // 11: proto.FloatingWindowResponse
	(*TabRequest)(nil),               // 12: proto.TabRequest
	(*TabResponse)(nil),              // 13: proto.TabResponse
	(*FocusRequest)(nil),             // 14: proto.FocusRequest
	(*FocusResponse)(nil),            // 15: proto.FocusResponse
	(*PublishRequest)(nil),           // 16: proto.PublishRequest
	(*PublishResponse)(nil),          // 17: proto.PublishResponse
	(*WindowCloseRequest)(nil),       // 18: proto.WindowCloseRequest
	(*WindowCloseResponse)(nil),      // 19: proto.WindowCloseResponse
	(*WindowSetContentRequest)(nil),  // 20: proto.WindowSetContentRequest
	(*WindowSetContentResponse)(nil), // 21: proto.WindowSetContentResponse
	(*WindowContentRequest)(nil),     // 22: proto.WindowContentRequest
	(*WindowContentResponse)(nil),    // 23: proto.WindowContentResponse
	(*Event)(nil),                    // 24: proto.Event
	(*Coordinates)(nil),              // 25: proto.Coordinates
}
var file_browser_proto_depIdxs = []int32{
	24, // 0: proto.Mapping.from:type_name -> proto.Event
	24, // 1: proto.Mapping.to:type_name -> proto.Event
	0,  // 2: proto.SplitRequest.orientation:type_name -> proto.Orientation
	0,  // 3: proto.BarRequest.orientation:type_name -> proto.Orientation
	25, // 4: proto.FloatingWindowRequest.at:type_name -> proto.Coordinates
	24, // 5: proto.PublishRequest.ev:type_name -> proto.Event
	1,  // 6: proto.ResourceOpener.Open:input_type -> proto.OpenResourceRequest
	3,  // 7: proto.Messenger.SetMessage:input_type -> proto.SetMessageRequest
	16, // 8: proto.EventPublisher.Publish:input_type -> proto.PublishRequest
	14, // 9: proto.WindowManager.Focus:input_type -> proto.FocusRequest
	6,  // 10: proto.WindowManager.Split:input_type -> proto.SplitRequest
	8,  // 11: proto.WindowManager.Bar:input_type -> proto.BarRequest
	10, // 12: proto.WindowManager.Floating:input_type -> proto.FloatingWindowRequest
	12, // 13: proto.WindowManager.Tab:input_type -> proto.TabRequest
	20, // 14: proto.Window.SetContent:input_type -> proto.WindowSetContentRequest
	22, // 15: proto.Window.Content:input_type -> proto.WindowContentRequest
	18, // 16: proto.Window.Close:input_type -> proto.WindowCloseRequest
	2,  // 17: proto.ResourceOpener.Open:output_type -> proto.OpenResourceResponse
	4,  // 18: proto.Messenger.SetMessage:output_type -> proto.SetMessageResponse
	17, // 19: proto.EventPublisher.Publish:output_type -> proto.PublishResponse
	15, // 20: proto.WindowManager.Focus:output_type -> proto.FocusResponse
	7,  // 21: proto.WindowManager.Split:output_type -> proto.SplitResponse
	9,  // 22: proto.WindowManager.Bar:output_type -> proto.BarResponse
	11, // 23: proto.WindowManager.Floating:output_type -> proto.FloatingWindowResponse
	13, // 24: proto.WindowManager.Tab:output_type -> proto.TabResponse
	21, // 25: proto.Window.SetContent:output_type -> proto.WindowSetContentResponse
	23, // 26: proto.Window.Content:output_type -> proto.WindowContentResponse
	19, // 27: proto.Window.Close:output_type -> proto.WindowCloseResponse
	17, // [17:28] is the sub-list for method output_type
	6,  // [6:17] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_browser_proto_init() }
func file_browser_proto_init() {
	if File_browser_proto != nil {
		return
	}
	file_term_proto_init()
	file_tui_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_browser_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenResourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenResourceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mapping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SplitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SplitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FloatingWindowRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FloatingWindowResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TabRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TabResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FocusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FocusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WindowCloseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WindowCloseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WindowSetContentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WindowSetContentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WindowContentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WindowContentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_browser_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_browser_proto_goTypes,
		DependencyIndexes: file_browser_proto_depIdxs,
		EnumInfos:         file_browser_proto_enumTypes,
		MessageInfos:      file_browser_proto_msgTypes,
	}.Build()
	File_browser_proto = out.File
	file_browser_proto_rawDesc = nil
	file_browser_proto_goTypes = nil
	file_browser_proto_depIdxs = nil
}
