syntax = "proto3";

option go_package = "github.com/ernestrc/go-tui/proto;proto";

import "term.proto";
import "tui.proto";

package proto;

message OpenResourceRequest {
    string resource = 1;
}

message OpenResourceResponse {
	uint64 handler_id = 1;
}

message SetMessageRequest {
	string msg = 1;
}

message SetMessageResponse {}

message Mapping {
	Event from = 1;
	Event to = 2;
}

enum Orientation {
	Default = 0;
	Top = 1;
	Bottom = 2;
	Left = 3;
	Right = 4;
}

message SplitRequest {
	uint64 handler_id = 1;
	Orientation orientation = 2;
}

message SplitResponse {
	uint64 window_id = 1;
}

message BarRequest {
	uint64 handler_id = 1;
	Orientation orientation = 2;
}

message BarResponse {
}

message FloatingWindowRequest {
	uint64 handler_id = 1;
	Coordinates at = 2;
	int32 height = 3;
	int32 width = 4;
}

message FloatingWindowResponse {
	uint64 window_id = 1;
}

message TabRequest {
	uint64 handler_id = 1;
    string resource_id = 2;
    string resource_name = 3;
}

message TabResponse {
	uint64 tab_handler_id = 1;
}

message FocusRequest {
}

message SetFocusRequest {
	uint64 window_id = 1;
}

message FocusResponse {
	uint64 window_id = 1;
}

message PublishRequest {
	Event ev = 1;
}

message PublishResponse {
}

service ResourceOpener {
	rpc Open(OpenResourceRequest) returns (OpenResourceResponse);
}

service Messenger {
	rpc SetMessage(SetMessageRequest) returns (SetMessageResponse);
}

service EventPublisher {
	rpc Publish(PublishRequest) returns (PublishResponse);
}

service WindowManager {
	rpc Focus(FocusRequest) returns (FocusResponse);
	rpc SetFocus(SetFocusRequest) returns (FocusResponse);
	rpc Split(SplitRequest) returns (SplitResponse);
	rpc Bar(BarRequest) returns (BarResponse);
	rpc Floating(FloatingWindowRequest) returns (FloatingWindowResponse);
	rpc Tab(TabRequest) returns (TabResponse);
}

message WindowCloseRequest {
}

message WindowCloseResponse {
}

message WindowSetContentRequest {
	uint64 handler_id = 1;
}

message WindowSetContentResponse {
}

message WindowContentRequest {
}

message WindowContentResponse {
	uint64 handler_id = 1;
}

service Window {
	rpc SetContent(WindowSetContentRequest) returns (WindowSetContentResponse);
	rpc Content(WindowContentRequest) returns (WindowContentResponse);
	rpc Close(WindowCloseRequest) returns (WindowCloseResponse);
}
