syntax = "proto3";

import "term.proto";
import "tui.proto";

package proto;

message EditRequest {
	string resource_name = 1;
	repeated CellRow buffer = 2;
}

message EditResponse {
	uint32 handler_id = 1;
}

message EditorEvent {
  enum Type {
	TypeOpen = 0;
	TypeClose = 1;
	TypeFlush = 2;
	TypeInsert = 3;
	TypeDelete = 4;
	TypeCommand = 5;
  }

  Type type = 1;
  string resource_name = 2;
  uint32 resource_id = 3;

  Coordinates start = 4;
  Coordinates end = 5;
  Coordinates from = 6;
  Coordinates to = 7;
  string content = 8;
}

message EditorSubscribeRequest {
	EditorEvent.Type type = 1;
	uint32 handler_id = 2;
}

message EditorSubscribeResponse {
}

message SetLocationListRequest {
	message Location {
		Coordinates from = 1;
		Coordinates to = 2;
		Attributes attr = 3;
		string msg = 4;
	}
	uint32 handler_id = 1;
	string list_id = 2;
	repeated Location locations = 3;
}

message SetLocationListResponse {}

message InsertRequest {
	uint32 handler_id = 1;
	Coordinates at = 2;
	string str = 3;
}

message InsertResponse {
	Coordinates from = 1;
	Coordinates to = 2;
}

message DeleteRequest {
	uint32 handler_id = 1;
	Coordinates from = 2;
	Coordinates to = 3;
}

message DeleteResponse {
	Coordinates start = 1;
	Coordinates end = 2;
	string str = 3;
}

message RawCellsRequest {
	uint32 handler_id = 1;
}

message RawCellsResponse {
	repeated CellRow rows = 1;
}

message MoveToLocationRequest {
	uint32 handler_id = 1;
	string list_id = 2;
}

message MoveToLocationResponse {
}

message RegisterCommandRequest {
	string command = 1;
	uint32 handler_id = 2;
}

message RegisterCommandResponse {}

message SetCursorRequest {
	Coordinates pos = 1;
	uint32 handler_id = 2;
}

message SetCursorResponse {
}

message CursorRequest {
	uint32 handler_id = 1;
}

message CursorResponse {
	Coordinates pos = 1;
}

service Editor {
	rpc Edit(EditRequest) returns (EditResponse);
	rpc Subscribe(EditorSubscribeRequest) returns (EditorSubscribeResponse);
	rpc Register(RegisterCommandRequest) returns (RegisterCommandResponse);
	rpc SetCursor(SetCursorRequest) returns (SetCursorResponse);
	rpc Cursor(CursorRequest) returns (CursorResponse);

	// locations
	rpc SetLocationList(SetLocationListRequest) returns (SetLocationListResponse);
	rpc MoveToNextLocation(MoveToLocationRequest) returns (MoveToLocationResponse);
	rpc MoveToPrevLocation(MoveToLocationRequest) returns (MoveToLocationResponse);


	// Writer
	rpc Insert(InsertRequest) returns (InsertResponse);
	rpc Delete(DeleteRequest) returns (DeleteResponse);

	// Reader
	rpc RawCells(RawCellsRequest) returns (RawCellsResponse);
}
