// Code generated by MockGen. DO NOT EDIT.
// Source: ./proto/broker.go

// Package proto is a generated GoMock package.
package proto

import (
	context "context"
	net "net"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	connectivity "google.golang.org/grpc/connectivity"
)

// MockMuxConn is a mock of MuxConn interface.
type MockMuxConn struct {
	ctrl     *gomock.Controller
	recorder *MockMuxConnMockRecorder
}

// MockMuxConnMockRecorder is the mock recorder for MockMuxConn.
type MockMuxConnMockRecorder struct {
	mock *MockMuxConn
}

// NewMockMuxConn creates a new mock instance.
func NewMockMuxConn(ctrl *gomock.Controller) *MockMuxConn {
	mock := &MockMuxConn{ctrl: ctrl}
	mock.recorder = &MockMuxConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMuxConn) EXPECT() *MockMuxConnMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockMuxConn) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockMuxConnMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMuxConn)(nil).Close))
}

// GetState mocks base method.
func (m *MockMuxConn) GetState() connectivity.State {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetState")
	ret0, _ := ret[0].(connectivity.State)
	return ret0
}

// GetState indicates an expected call of GetState.
func (mr *MockMuxConnMockRecorder) GetState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetState", reflect.TypeOf((*MockMuxConn)(nil).GetState))
}

// Invoke mocks base method.
func (m *MockMuxConn) Invoke(ctx context.Context, method string, args, reply interface{}, opts ...grpc.CallOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, method, args, reply}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Invoke", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Invoke indicates an expected call of Invoke.
func (mr *MockMuxConnMockRecorder) Invoke(ctx, method, args, reply interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, method, args, reply}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invoke", reflect.TypeOf((*MockMuxConn)(nil).Invoke), varargs...)
}

// NewStream mocks base method.
func (m *MockMuxConn) NewStream(ctx context.Context, desc *grpc.StreamDesc, method string, opts ...grpc.CallOption) (grpc.ClientStream, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, desc, method}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewStream", varargs...)
	ret0, _ := ret[0].(grpc.ClientStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewStream indicates an expected call of NewStream.
func (mr *MockMuxConnMockRecorder) NewStream(ctx, desc, method interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, desc, method}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewStream", reflect.TypeOf((*MockMuxConn)(nil).NewStream), varargs...)
}

// WaitForStateChange mocks base method.
func (m *MockMuxConn) WaitForStateChange(ctx context.Context, sourceState connectivity.State) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForStateChange", ctx, sourceState)
	ret0, _ := ret[0].(bool)
	return ret0
}

// WaitForStateChange indicates an expected call of WaitForStateChange.
func (mr *MockMuxConnMockRecorder) WaitForStateChange(ctx, sourceState interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForStateChange", reflect.TypeOf((*MockMuxConn)(nil).WaitForStateChange), ctx, sourceState)
}

// MockMuxServer is a mock of MuxServer interface.
type MockMuxServer struct {
	ctrl     *gomock.Controller
	recorder *MockMuxServerMockRecorder
}

// MockMuxServerMockRecorder is the mock recorder for MockMuxServer.
type MockMuxServerMockRecorder struct {
	mock *MockMuxServer
}

// NewMockMuxServer creates a new mock instance.
func NewMockMuxServer(ctrl *gomock.Controller) *MockMuxServer {
	mock := &MockMuxServer{ctrl: ctrl}
	mock.recorder = &MockMuxServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMuxServer) EXPECT() *MockMuxServerMockRecorder {
	return m.recorder
}

// GRPC mocks base method.
func (m *MockMuxServer) GRPC() *grpc.Server {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GRPC")
	ret0, _ := ret[0].(*grpc.Server)
	return ret0
}

// GRPC indicates an expected call of GRPC.
func (mr *MockMuxServerMockRecorder) GRPC() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GRPC", reflect.TypeOf((*MockMuxServer)(nil).GRPC))
}

// GracefulStop mocks base method.
func (m *MockMuxServer) GracefulStop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GracefulStop")
}

// GracefulStop indicates an expected call of GracefulStop.
func (mr *MockMuxServerMockRecorder) GracefulStop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GracefulStop", reflect.TypeOf((*MockMuxServer)(nil).GracefulStop))
}

// Serve mocks base method.
func (m *MockMuxServer) Serve(lis net.Listener) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Serve", lis)
	ret0, _ := ret[0].(error)
	return ret0
}

// Serve indicates an expected call of Serve.
func (mr *MockMuxServerMockRecorder) Serve(lis interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Serve", reflect.TypeOf((*MockMuxServer)(nil).Serve), lis)
}

// Stop mocks base method.
func (m *MockMuxServer) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockMuxServerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockMuxServer)(nil).Stop))
}

// MockMuxBroker is a mock of MuxBroker interface.
type MockMuxBroker struct {
	ctrl     *gomock.Controller
	recorder *MockMuxBrokerMockRecorder
}

// MockMuxBrokerMockRecorder is the mock recorder for MockMuxBroker.
type MockMuxBrokerMockRecorder struct {
	mock *MockMuxBroker
}

// NewMockMuxBroker creates a new mock instance.
func NewMockMuxBroker(ctrl *gomock.Controller) *MockMuxBroker {
	mock := &MockMuxBroker{ctrl: ctrl}
	mock.recorder = &MockMuxBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMuxBroker) EXPECT() *MockMuxBrokerMockRecorder {
	return m.recorder
}

// Accept mocks base method.
func (m *MockMuxBroker) Accept(id uint32) (net.Listener, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Accept", id)
	ret0, _ := ret[0].(net.Listener)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Accept indicates an expected call of Accept.
func (mr *MockMuxBrokerMockRecorder) Accept(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accept", reflect.TypeOf((*MockMuxBroker)(nil).Accept), id)
}

// AcceptAndServe mocks base method.
func (m *MockMuxBroker) AcceptAndServe(ID uint32, srv func([]grpc.ServerOption) MuxServer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AcceptAndServe", ID, srv)
}

// AcceptAndServe indicates an expected call of AcceptAndServe.
func (mr *MockMuxBrokerMockRecorder) AcceptAndServe(ID, srv interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptAndServe", reflect.TypeOf((*MockMuxBroker)(nil).AcceptAndServe), ID, srv)
}

// Cleanup mocks base method.
func (m *MockMuxBroker) Cleanup(ID uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cleanup", ID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockMuxBrokerMockRecorder) Cleanup(ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockMuxBroker)(nil).Cleanup), ID)
}

// Close mocks base method.
func (m *MockMuxBroker) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockMuxBrokerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMuxBroker)(nil).Close))
}

// Dial mocks base method.
func (m *MockMuxBroker) Dial(ID uint32) (MuxConn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dial", ID)
	ret0, _ := ret[0].(MuxConn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dial indicates an expected call of Dial.
func (mr *MockMuxBrokerMockRecorder) Dial(ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dial", reflect.TypeOf((*MockMuxBroker)(nil).Dial), ID)
}

// NextId mocks base method.
func (m *MockMuxBroker) NextId() uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextId")
	ret0, _ := ret[0].(uint32)
	return ret0
}

// NextId indicates an expected call of NextId.
func (mr *MockMuxBrokerMockRecorder) NextId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextId", reflect.TypeOf((*MockMuxBroker)(nil).NextId))
}
