// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: rpc/grantee.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GranteeClient is the client API for Grantee service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GranteeClient interface {
	Permissions(ctx context.Context, in *PermRequest, opts ...grpc.CallOption) (*PermResponse, error)
	OnGrant(ctx context.Context, in *OnPermGrantRequest, opts ...grpc.CallOption) (*OnPermGrantResponse, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type granteeClient struct {
	cc grpc.ClientConnInterface
}

func NewGranteeClient(cc grpc.ClientConnInterface) GranteeClient {
	return &granteeClient{cc}
}

func (c *granteeClient) Permissions(ctx context.Context, in *PermRequest, opts ...grpc.CallOption) (*PermResponse, error) {
	out := new(PermResponse)
	err := c.cc.Invoke(ctx, "/extension.Grantee/Permissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *granteeClient) OnGrant(ctx context.Context, in *OnPermGrantRequest, opts ...grpc.CallOption) (*OnPermGrantResponse, error) {
	out := new(OnPermGrantResponse)
	err := c.cc.Invoke(ctx, "/extension.Grantee/OnGrant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *granteeClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, "/extension.Grantee/Shutdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *granteeClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/extension.Grantee/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GranteeServer is the server API for Grantee service.
// All implementations must embed UnimplementedGranteeServer
// for forward compatibility
type GranteeServer interface {
	Permissions(context.Context, *PermRequest) (*PermResponse, error)
	OnGrant(context.Context, *OnPermGrantRequest) (*OnPermGrantResponse, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedGranteeServer()
}

// UnimplementedGranteeServer must be embedded to have forward compatible implementations.
type UnimplementedGranteeServer struct {
}

func (UnimplementedGranteeServer) Permissions(context.Context, *PermRequest) (*PermResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Permissions not implemented")
}
func (UnimplementedGranteeServer) OnGrant(context.Context, *OnPermGrantRequest) (*OnPermGrantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnGrant not implemented")
}
func (UnimplementedGranteeServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedGranteeServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedGranteeServer) mustEmbedUnimplementedGranteeServer() {}

// UnsafeGranteeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GranteeServer will
// result in compilation errors.
type UnsafeGranteeServer interface {
	mustEmbedUnimplementedGranteeServer()
}

func RegisterGranteeServer(s grpc.ServiceRegistrar, srv GranteeServer) {
	s.RegisterService(&Grantee_ServiceDesc, srv)
}

func _Grantee_Permissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GranteeServer).Permissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/extension.Grantee/Permissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GranteeServer).Permissions(ctx, req.(*PermRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grantee_OnGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnPermGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GranteeServer).OnGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/extension.Grantee/OnGrant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GranteeServer).OnGrant(ctx, req.(*OnPermGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grantee_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GranteeServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/extension.Grantee/Shutdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GranteeServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grantee_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GranteeServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/extension.Grantee/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GranteeServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Grantee_ServiceDesc is the grpc.ServiceDesc for Grantee service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Grantee_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "extension.Grantee",
	HandlerType: (*GranteeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Permissions",
			Handler:    _Grantee_Permissions_Handler,
		},
		{
			MethodName: "OnGrant",
			Handler:    _Grantee_OnGrant_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Grantee_Shutdown_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Grantee_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/grantee.proto",
}
