// Unstable Build LLC ("COMPANY") CONFIDENTIAL
//
// Unpublished Copyright (c) 2017-2024 Unstable Build, All Rights Reserved.
//
// NOTICE: All information contained herein is, and remains the property of COMPANY.
// The intellectual and technical concepts contained herein are proprietary to
// COMPANY and may be covered by U.S. and Foreign Patents, patents in process,
// and are protected by trade secret or copyright law. Dissemination of this information
// or reproduction of this material is strictly forbidden unless prior written permission
// is obtained from COMPANY. Access to the source code contained herein is hereby
// forbidden to anyone except current COMPANY employees, managers or contractors who
// have executed Confidentiality and Non-disclosure agreements explicitly covering such access.
//
// The copyright notice above does not evidence any actual or intended publication or
// disclosure of this source code, which includes information that is confidential and/or
// proprietary, and is a trade secret, of COMPANY. ANY REPRODUCTION, MODIFICATION,
// DISTRIBUTION, PUBLIC  PERFORMANCE, OR PUBLIC DISPLAY OF OR THROUGH USE OF THIS SOURCE CODE
// WITHOUT  THE EXPRESS WRITTEN CONSENT OF COMPANY IS STRICTLY PROHIBITED, AND IN
// VIOLATION OF APPLICABLE LAWS AND INTERNATIONAL TREATIES. THE RECEIPT OR POSSESSION OF
// THIS SOURCE CODE AND/OR RELATED INFORMATION DOES NOT CONVEY OR IMPLY ANY RIGHTS TO
// REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS, OR TO MANUFACTURE, USE, OR SELL
// ANYTHING THAT IT MAY DESCRIBE, IN WHOLE OR IN PART.

package notifications

import (
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/unstablebuild/rune-go-sdk/component"
	"github.com/unstablebuild/rune-go-sdk/component/comptest"
	"github.com/unstablebuild/rune-go-sdk/term"
)

func TestComponentDraw(t *testing.T) {
	inner := &component.TestComponent{Ch: 'X'}

	c := New(inner, Config{
		AutoClose:   1 * time.Hour,
		ProgressBar: true,
		Width:       10,
		ProgressRunes: ProgressRunes{
			Start:      '{',
			Current:    '-',
			CurrentTip: '>',
			Remain:     ' ',
			End:        '}',
		},
	})
	c.Resize(40, 15)

	w := term.NewStringWriter(40, 15)

	var id string
	tests := []comptest.TestCase{
		{
			nil, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`,
		}, {
			func() { c.Notify(LevelInfo, "hello world") }, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ hello  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ world  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX{>       }
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`,
		}, {
			func() { c.Resize(2, 15) }, `
                                        
he                                      
ll                                      
o                                       
wo                                      
rl                                      
d                                       
{}                                      
XX                                      
XX                                      
XX                                      
XX                                      
XX                                      
XX                                      
XX                                      `,
		}, {
			func() { c.Resize(4, 15) }, `
┌──┐                                    
│he│                                    
│ll│                                    
│o │                                    
│wo│                                    
│rl│                                    
│d │                                    
{> }                                    
XXXX                                    
XXXX                                    
XXXX                                    
XXXX                                    
XXXX                                    
XXXX                                    
XXXX                                    `,
		}, {
			func() { c.Resize(40, 15) }, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ hello  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ world  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX{>       }
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`,
		}, {
			func() { c.Notify(LevelInfo, "Does not fit I think") }, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ Does   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ not    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ fit I  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ think  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX{>       }
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ hello  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ world  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX{>       }
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`,
		}, {
			func() { c.Notify(LevelInfo, "This time it won't fit for sure") }, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ This   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ time   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ it     │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ won't  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ fit    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ for    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ sure   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX{>       }
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ Does   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ not    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ fit I  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ think  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX{>       }`,
		}, {
			func() { c.Notify(LevelInfo, "This time it won't fit for SURE SURE") }, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ This   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ time   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ it     │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ won't  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ fit    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ for    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ SURE   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ SURE   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX{>       }
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ This   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ time   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ it     │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ won't  │`,
		}, {
			func() { c.Resize(20, 10) }, `
XXXXXXXXXX┌────────┐                    
XXXXXXXXXX│ This   │                    
XXXXXXXXXX│ time   │                    
XXXXXXXXXX│ it     │                    
XXXXXXXXXX│ won't  │                    
XXXXXXXXXX│ fit    │                    
XXXXXXXXXX│ for    │                    
XXXXXXXXXX│ SURE   │                    
XXXXXXXXXX│ SURE   │                    
XXXXXXXXXX{>       }                    
                                        
                                        
                                        
                                        
                                        `,
		}, {
			func() { c.Resize(40, 15) }, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ This   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ time   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ it     │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ won't  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ fit    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ for    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ SURE   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ SURE   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX{>       }
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ This   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ time   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ it     │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ won't  │`,
		}, {
			func() {
				c.PauseAll()
				c.ResumeAll()
				c.PauseAll()
				c.ResumeAll()
			}, /* simply tests data races and deadlocks */ `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ This   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ time   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ it     │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ won't  │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ fit    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ for    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ SURE   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ SURE   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX{>       }
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ This   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ time   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ it     │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ won't  │`,
		}, {
			func() { c.CloseAll() }, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`,
		}, {
			func() {
				id := c.Notify(LevelInfo, "hello world")
				c.UpdateProgress(id, "hola mon", 0, 10)

			}, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ hola   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ mon    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX{        }
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`,
		}, {
			func() {
				id := c.Notify(LevelInfo, "hello world")
				c.UpdateProgress(id, "hola mon", 1, 10)

			}, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ hola   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ mon    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX{>       }
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`,
		}, {
			func() {
				id := c.Notify(LevelInfo, "hello world")
				c.UpdateProgress(id, "hola mon", 8, 10)

			}, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ hola   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ mon    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX{------->}
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`,
		}, {
			func() {
				id = c.Notify(LevelInfo, "hello world")
				c.UpdateProgress(id, "h0l4 m0n", 1, 10)
				c.UpdateProgress(id, "hola mon", 5, 10)
			}, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ hola   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ mon    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX{---->   }
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`,
		}, {
			func() {
				c.UpdateProgress(id, "hola mon boig", 6, 10)
			}, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ hola   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ mon    │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ boig   │
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX{----->  }
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`,
		},
	}

	comptest.TestComponent(t, c, w, tests)
}

func TestComponentDrawWithPadding(t *testing.T) {
	inner := &component.TestComponent{Ch: 'X'}

	c := New(inner, Config{
		AutoClose:   1 * time.Hour,
		ProgressBar: true,
		Width:       10,
		Padding:     1,
		ProgressRunes: ProgressRunes{
			Start:      '{',
			Current:    '-',
			CurrentTip: '>',
			Remain:     ' ',
			End:        '}',
		},
	})
	c.Resize(40, 15)

	w := term.NewStringWriter(40, 15)

	var id string
	tests := []comptest.TestCase{
		{
			func() { id = c.Notify(LevelInfo, "hello world") }, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ hello  │X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ world  │X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX{>       }X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`,
		}, {
			func() { c.Resize(2, 15) }, `
XX                                      
                                        
he                                      
ll                                      
o                                       
wo                                      
rl                                      
d                                       
{}                                      
XX                                      
XX                                      
XX                                      
XX                                      
XX                                      
XX                                      `,
		}, {
			func() { c.Resize(4, 15) }, `
XXXX                                    
┌──┐                                    
│he│                                    
│ll│                                    
│o │                                    
│wo│                                    
│rl│                                    
│d │                                    
{> }                                    
XXXX                                    
XXXX                                    
XXXX                                    
XXXX                                    
XXXX                                    
XXXX                                    `,
		}, {
			func() { c.Resize(40, 15) }, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ hello  │X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ world  │X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX{>       }X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`,
		}, {
			func() {
				c.UpdateProgress(id, "Does not fit I think", 1, 10)
			}, `
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX┌────────┐X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ Does   │X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ not    │X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ fit I  │X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX│ think  │X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXX{>       }X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`,
		},
	}

	comptest.TestComponent(t, c, w, tests)
}

func TestNotificationID(t *testing.T) {
	t.Run("two notifications with the same message have the same ID", func(t *testing.T) {
		c := New(&component.TestComponent{}, Config{Width: 10, AutoClose: 10 * time.Second})
		assert.Equal(t, c.ID(LevelError, "test: 1"), c.ID(LevelWarn, "test: 1"))
	})
	t.Run("two notifications with different messages have different IDs", func(t *testing.T) {
		c := New(&component.TestComponent{}, Config{Width: 10, AutoClose: 10 * time.Second})
		assert.NotEqual(t, c.ID(LevelError, "test: 1"), c.ID(LevelError, "test: 2"))
	})
}
