// Code generated by MockGen. DO NOT EDIT.
// Source: ./text/mouse.go

// Package text is a generated GoMock package.
package text

import (
	reflect "reflect"

	term "github.com/ernestrc/go-tui/term"
	gomock "github.com/golang/mock/gomock"
)

// MockMouseDelegate is a mock of MouseDelegate interface.
type MockMouseDelegate struct {
	ctrl     *gomock.Controller
	recorder *MockMouseDelegateMockRecorder
}

// MockMouseDelegateMockRecorder is the mock recorder for MockMouseDelegate.
type MockMouseDelegateMockRecorder struct {
	mock *MockMouseDelegate
}

// NewMockMouseDelegate creates a new mock instance.
func NewMockMouseDelegate(ctrl *gomock.Controller) *MockMouseDelegate {
	mock := &MockMouseDelegate{ctrl: ctrl}
	mock.recorder = &MockMouseDelegateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMouseDelegate) EXPECT() *MockMouseDelegateMockRecorder {
	return m.recorder
}

// ClearSelection mocks base method.
func (m *MockMouseDelegate) ClearSelection() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearSelection")
}

// ClearSelection indicates an expected call of ClearSelection.
func (mr *MockMouseDelegateMockRecorder) ClearSelection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearSelection", reflect.TypeOf((*MockMouseDelegate)(nil).ClearSelection))
}

// Height mocks base method.
func (m *MockMouseDelegate) Height() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Height")
	ret0, _ := ret[0].(int)
	return ret0
}

// Height indicates an expected call of Height.
func (mr *MockMouseDelegateMockRecorder) Height() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Height", reflect.TypeOf((*MockMouseDelegate)(nil).Height))
}

// OnAction mocks base method.
func (m *MockMouseDelegate) OnAction(pos term.Coordinates, action MouseAction) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnAction", pos, action)
	ret0, _ := ret[0].(bool)
	return ret0
}

// OnAction indicates an expected call of OnAction.
func (mr *MockMouseDelegateMockRecorder) OnAction(pos, action interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnAction", reflect.TypeOf((*MockMouseDelegate)(nil).OnAction), pos, action)
}

// ScrollDown mocks base method.
func (m *MockMouseDelegate) ScrollDown(n int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScrollDown", n)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ScrollDown indicates an expected call of ScrollDown.
func (mr *MockMouseDelegateMockRecorder) ScrollDown(n interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScrollDown", reflect.TypeOf((*MockMouseDelegate)(nil).ScrollDown), n)
}

// ScrollUp mocks base method.
func (m *MockMouseDelegate) ScrollUp(n int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScrollUp", n)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ScrollUp indicates an expected call of ScrollUp.
func (mr *MockMouseDelegateMockRecorder) ScrollUp(n interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScrollUp", reflect.TypeOf((*MockMouseDelegate)(nil).ScrollUp), n)
}

// SelectLine mocks base method.
func (m *MockMouseDelegate) SelectLine(y int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SelectLine", y)
}

// SelectLine indicates an expected call of SelectLine.
func (mr *MockMouseDelegateMockRecorder) SelectLine(y interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectLine", reflect.TypeOf((*MockMouseDelegate)(nil).SelectLine), y)
}

// SelectWordAt mocks base method.
func (m *MockMouseDelegate) SelectWordAt(pos term.Coordinates) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SelectWordAt", pos)
}

// SelectWordAt indicates an expected call of SelectWordAt.
func (mr *MockMouseDelegateMockRecorder) SelectWordAt(pos interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectWordAt", reflect.TypeOf((*MockMouseDelegate)(nil).SelectWordAt), pos)
}

// SetSelectionEnd mocks base method.
func (m *MockMouseDelegate) SetSelectionEnd(pos term.Coordinates) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSelectionEnd", pos)
}

// SetSelectionEnd indicates an expected call of SetSelectionEnd.
func (mr *MockMouseDelegateMockRecorder) SetSelectionEnd(pos interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSelectionEnd", reflect.TypeOf((*MockMouseDelegate)(nil).SetSelectionEnd), pos)
}

// SetSelectionStart mocks base method.
func (m *MockMouseDelegate) SetSelectionStart(pos term.Coordinates) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSelectionStart", pos)
}

// SetSelectionStart indicates an expected call of SetSelectionStart.
func (mr *MockMouseDelegateMockRecorder) SetSelectionStart(pos interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSelectionStart", reflect.TypeOf((*MockMouseDelegate)(nil).SetSelectionStart), pos)
}

// Width mocks base method.
func (m *MockMouseDelegate) Width() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Width")
	ret0, _ := ret[0].(int)
	return ret0
}

// Width indicates an expected call of Width.
func (mr *MockMouseDelegateMockRecorder) Width() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Width", reflect.TypeOf((*MockMouseDelegate)(nil).Width))
}
