// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: rpc/browser.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ResourceOpenerClient is the client API for ResourceOpener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResourceOpenerClient interface {
	Open(ctx context.Context, in *OpenResourceRequest, opts ...grpc.CallOption) (*OpenResourceResponse, error)
}

type resourceOpenerClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceOpenerClient(cc grpc.ClientConnInterface) ResourceOpenerClient {
	return &resourceOpenerClient{cc}
}

func (c *resourceOpenerClient) Open(ctx context.Context, in *OpenResourceRequest, opts ...grpc.CallOption) (*OpenResourceResponse, error) {
	out := new(OpenResourceResponse)
	err := c.cc.Invoke(ctx, "/browser.ResourceOpener/Open", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceOpenerServer is the server API for ResourceOpener service.
// All implementations must embed UnimplementedResourceOpenerServer
// for forward compatibility
type ResourceOpenerServer interface {
	Open(context.Context, *OpenResourceRequest) (*OpenResourceResponse, error)
	mustEmbedUnimplementedResourceOpenerServer()
}

// UnimplementedResourceOpenerServer must be embedded to have forward compatible implementations.
type UnimplementedResourceOpenerServer struct {
}

func (UnimplementedResourceOpenerServer) Open(context.Context, *OpenResourceRequest) (*OpenResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Open not implemented")
}
func (UnimplementedResourceOpenerServer) mustEmbedUnimplementedResourceOpenerServer() {}

// UnsafeResourceOpenerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceOpenerServer will
// result in compilation errors.
type UnsafeResourceOpenerServer interface {
	mustEmbedUnimplementedResourceOpenerServer()
}

func RegisterResourceOpenerServer(s grpc.ServiceRegistrar, srv ResourceOpenerServer) {
	s.RegisterService(&ResourceOpener_ServiceDesc, srv)
}

func _ResourceOpener_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceOpenerServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/browser.ResourceOpener/Open",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceOpenerServer).Open(ctx, req.(*OpenResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResourceOpener_ServiceDesc is the grpc.ServiceDesc for ResourceOpener service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceOpener_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "browser.ResourceOpener",
	HandlerType: (*ResourceOpenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Open",
			Handler:    _ResourceOpener_Open_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/browser.proto",
}

// NotificationsClient is the client API for Notifications service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationsClient interface {
	Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error)
}

type notificationsClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationsClient(cc grpc.ClientConnInterface) NotificationsClient {
	return &notificationsClient{cc}
}

func (c *notificationsClient) Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error) {
	out := new(NotifyResponse)
	err := c.cc.Invoke(ctx, "/browser.Notifications/Notify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationsServer is the server API for Notifications service.
// All implementations must embed UnimplementedNotificationsServer
// for forward compatibility
type NotificationsServer interface {
	Notify(context.Context, *NotifyRequest) (*NotifyResponse, error)
	mustEmbedUnimplementedNotificationsServer()
}

// UnimplementedNotificationsServer must be embedded to have forward compatible implementations.
type UnimplementedNotificationsServer struct {
}

func (UnimplementedNotificationsServer) Notify(context.Context, *NotifyRequest) (*NotifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedNotificationsServer) mustEmbedUnimplementedNotificationsServer() {}

// UnsafeNotificationsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationsServer will
// result in compilation errors.
type UnsafeNotificationsServer interface {
	mustEmbedUnimplementedNotificationsServer()
}

func RegisterNotificationsServer(s grpc.ServiceRegistrar, srv NotificationsServer) {
	s.RegisterService(&Notifications_ServiceDesc, srv)
}

func _Notifications_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationsServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/browser.Notifications/Notify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationsServer).Notify(ctx, req.(*NotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Notifications_ServiceDesc is the grpc.ServiceDesc for Notifications service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Notifications_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "browser.Notifications",
	HandlerType: (*NotificationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Notify",
			Handler:    _Notifications_Notify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/browser.proto",
}

// EventPublisherClient is the client API for EventPublisher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventPublisherClient interface {
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
}

type eventPublisherClient struct {
	cc grpc.ClientConnInterface
}

func NewEventPublisherClient(cc grpc.ClientConnInterface) EventPublisherClient {
	return &eventPublisherClient{cc}
}

func (c *eventPublisherClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, "/browser.EventPublisher/Publish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventPublisherServer is the server API for EventPublisher service.
// All implementations must embed UnimplementedEventPublisherServer
// for forward compatibility
type EventPublisherServer interface {
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	mustEmbedUnimplementedEventPublisherServer()
}

// UnimplementedEventPublisherServer must be embedded to have forward compatible implementations.
type UnimplementedEventPublisherServer struct {
}

func (UnimplementedEventPublisherServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedEventPublisherServer) mustEmbedUnimplementedEventPublisherServer() {}

// UnsafeEventPublisherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventPublisherServer will
// result in compilation errors.
type UnsafeEventPublisherServer interface {
	mustEmbedUnimplementedEventPublisherServer()
}

func RegisterEventPublisherServer(s grpc.ServiceRegistrar, srv EventPublisherServer) {
	s.RegisterService(&EventPublisher_ServiceDesc, srv)
}

func _EventPublisher_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventPublisherServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/browser.EventPublisher/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventPublisherServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventPublisher_ServiceDesc is the grpc.ServiceDesc for EventPublisher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventPublisher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "browser.EventPublisher",
	HandlerType: (*EventPublisherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _EventPublisher_Publish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/browser.proto",
}

// WindowManagerClient is the client API for WindowManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WindowManagerClient interface {
	Focus(ctx context.Context, in *FocusRequest, opts ...grpc.CallOption) (*FocusResponse, error)
	SetFocus(ctx context.Context, in *SetFocusRequest, opts ...grpc.CallOption) (*FocusResponse, error)
	Split(ctx context.Context, in *SplitRequest, opts ...grpc.CallOption) (*SplitResponse, error)
	Bar(ctx context.Context, in *BarRequest, opts ...grpc.CallOption) (*BarResponse, error)
	Floating(ctx context.Context, in *FloatingWindowRequest, opts ...grpc.CallOption) (*FloatingWindowResponse, error)
	Tab(ctx context.Context, in *TabRequest, opts ...grpc.CallOption) (*TabResponse, error)
	// window
	SetContent(ctx context.Context, in *WindowSetContentRequest, opts ...grpc.CallOption) (*WindowSetContentResponse, error)
	Content(ctx context.Context, in *WindowContentRequest, opts ...grpc.CallOption) (*WindowContentResponse, error)
	Close(ctx context.Context, in *WindowCloseRequest, opts ...grpc.CallOption) (*WindowCloseResponse, error)
}

type windowManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewWindowManagerClient(cc grpc.ClientConnInterface) WindowManagerClient {
	return &windowManagerClient{cc}
}

func (c *windowManagerClient) Focus(ctx context.Context, in *FocusRequest, opts ...grpc.CallOption) (*FocusResponse, error) {
	out := new(FocusResponse)
	err := c.cc.Invoke(ctx, "/browser.WindowManager/Focus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *windowManagerClient) SetFocus(ctx context.Context, in *SetFocusRequest, opts ...grpc.CallOption) (*FocusResponse, error) {
	out := new(FocusResponse)
	err := c.cc.Invoke(ctx, "/browser.WindowManager/SetFocus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *windowManagerClient) Split(ctx context.Context, in *SplitRequest, opts ...grpc.CallOption) (*SplitResponse, error) {
	out := new(SplitResponse)
	err := c.cc.Invoke(ctx, "/browser.WindowManager/Split", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *windowManagerClient) Bar(ctx context.Context, in *BarRequest, opts ...grpc.CallOption) (*BarResponse, error) {
	out := new(BarResponse)
	err := c.cc.Invoke(ctx, "/browser.WindowManager/Bar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *windowManagerClient) Floating(ctx context.Context, in *FloatingWindowRequest, opts ...grpc.CallOption) (*FloatingWindowResponse, error) {
	out := new(FloatingWindowResponse)
	err := c.cc.Invoke(ctx, "/browser.WindowManager/Floating", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *windowManagerClient) Tab(ctx context.Context, in *TabRequest, opts ...grpc.CallOption) (*TabResponse, error) {
	out := new(TabResponse)
	err := c.cc.Invoke(ctx, "/browser.WindowManager/Tab", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *windowManagerClient) SetContent(ctx context.Context, in *WindowSetContentRequest, opts ...grpc.CallOption) (*WindowSetContentResponse, error) {
	out := new(WindowSetContentResponse)
	err := c.cc.Invoke(ctx, "/browser.WindowManager/SetContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *windowManagerClient) Content(ctx context.Context, in *WindowContentRequest, opts ...grpc.CallOption) (*WindowContentResponse, error) {
	out := new(WindowContentResponse)
	err := c.cc.Invoke(ctx, "/browser.WindowManager/Content", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *windowManagerClient) Close(ctx context.Context, in *WindowCloseRequest, opts ...grpc.CallOption) (*WindowCloseResponse, error) {
	out := new(WindowCloseResponse)
	err := c.cc.Invoke(ctx, "/browser.WindowManager/Close", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WindowManagerServer is the server API for WindowManager service.
// All implementations must embed UnimplementedWindowManagerServer
// for forward compatibility
type WindowManagerServer interface {
	Focus(context.Context, *FocusRequest) (*FocusResponse, error)
	SetFocus(context.Context, *SetFocusRequest) (*FocusResponse, error)
	Split(context.Context, *SplitRequest) (*SplitResponse, error)
	Bar(context.Context, *BarRequest) (*BarResponse, error)
	Floating(context.Context, *FloatingWindowRequest) (*FloatingWindowResponse, error)
	Tab(context.Context, *TabRequest) (*TabResponse, error)
	// window
	SetContent(context.Context, *WindowSetContentRequest) (*WindowSetContentResponse, error)
	Content(context.Context, *WindowContentRequest) (*WindowContentResponse, error)
	Close(context.Context, *WindowCloseRequest) (*WindowCloseResponse, error)
	mustEmbedUnimplementedWindowManagerServer()
}

// UnimplementedWindowManagerServer must be embedded to have forward compatible implementations.
type UnimplementedWindowManagerServer struct {
}

func (UnimplementedWindowManagerServer) Focus(context.Context, *FocusRequest) (*FocusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Focus not implemented")
}
func (UnimplementedWindowManagerServer) SetFocus(context.Context, *SetFocusRequest) (*FocusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetFocus not implemented")
}
func (UnimplementedWindowManagerServer) Split(context.Context, *SplitRequest) (*SplitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Split not implemented")
}
func (UnimplementedWindowManagerServer) Bar(context.Context, *BarRequest) (*BarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bar not implemented")
}
func (UnimplementedWindowManagerServer) Floating(context.Context, *FloatingWindowRequest) (*FloatingWindowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Floating not implemented")
}
func (UnimplementedWindowManagerServer) Tab(context.Context, *TabRequest) (*TabResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tab not implemented")
}
func (UnimplementedWindowManagerServer) SetContent(context.Context, *WindowSetContentRequest) (*WindowSetContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetContent not implemented")
}
func (UnimplementedWindowManagerServer) Content(context.Context, *WindowContentRequest) (*WindowContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Content not implemented")
}
func (UnimplementedWindowManagerServer) Close(context.Context, *WindowCloseRequest) (*WindowCloseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedWindowManagerServer) mustEmbedUnimplementedWindowManagerServer() {}

// UnsafeWindowManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WindowManagerServer will
// result in compilation errors.
type UnsafeWindowManagerServer interface {
	mustEmbedUnimplementedWindowManagerServer()
}

func RegisterWindowManagerServer(s grpc.ServiceRegistrar, srv WindowManagerServer) {
	s.RegisterService(&WindowManager_ServiceDesc, srv)
}

func _WindowManager_Focus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FocusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindowManagerServer).Focus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/browser.WindowManager/Focus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindowManagerServer).Focus(ctx, req.(*FocusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WindowManager_SetFocus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetFocusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindowManagerServer).SetFocus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/browser.WindowManager/SetFocus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindowManagerServer).SetFocus(ctx, req.(*SetFocusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WindowManager_Split_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SplitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindowManagerServer).Split(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/browser.WindowManager/Split",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindowManagerServer).Split(ctx, req.(*SplitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WindowManager_Bar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindowManagerServer).Bar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/browser.WindowManager/Bar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindowManagerServer).Bar(ctx, req.(*BarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WindowManager_Floating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FloatingWindowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindowManagerServer).Floating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/browser.WindowManager/Floating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindowManagerServer).Floating(ctx, req.(*FloatingWindowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WindowManager_Tab_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TabRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindowManagerServer).Tab(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/browser.WindowManager/Tab",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindowManagerServer).Tab(ctx, req.(*TabRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WindowManager_SetContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WindowSetContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindowManagerServer).SetContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/browser.WindowManager/SetContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindowManagerServer).SetContent(ctx, req.(*WindowSetContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WindowManager_Content_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WindowContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindowManagerServer).Content(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/browser.WindowManager/Content",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindowManagerServer).Content(ctx, req.(*WindowContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WindowManager_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WindowCloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindowManagerServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/browser.WindowManager/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindowManagerServer).Close(ctx, req.(*WindowCloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WindowManager_ServiceDesc is the grpc.ServiceDesc for WindowManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WindowManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "browser.WindowManager",
	HandlerType: (*WindowManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Focus",
			Handler:    _WindowManager_Focus_Handler,
		},
		{
			MethodName: "SetFocus",
			Handler:    _WindowManager_SetFocus_Handler,
		},
		{
			MethodName: "Split",
			Handler:    _WindowManager_Split_Handler,
		},
		{
			MethodName: "Bar",
			Handler:    _WindowManager_Bar_Handler,
		},
		{
			MethodName: "Floating",
			Handler:    _WindowManager_Floating_Handler,
		},
		{
			MethodName: "Tab",
			Handler:    _WindowManager_Tab_Handler,
		},
		{
			MethodName: "SetContent",
			Handler:    _WindowManager_SetContent_Handler,
		},
		{
			MethodName: "Content",
			Handler:    _WindowManager_Content_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _WindowManager_Close_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/browser.proto",
}

// FloatingClient is the client API for Floating service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FloatingClient interface {
	Dimensions(ctx context.Context, in *DimensionsRequest, opts ...grpc.CallOption) (*DimensionsResponse, error)
}

type floatingClient struct {
	cc grpc.ClientConnInterface
}

func NewFloatingClient(cc grpc.ClientConnInterface) FloatingClient {
	return &floatingClient{cc}
}

func (c *floatingClient) Dimensions(ctx context.Context, in *DimensionsRequest, opts ...grpc.CallOption) (*DimensionsResponse, error) {
	out := new(DimensionsResponse)
	err := c.cc.Invoke(ctx, "/browser.Floating/Dimensions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FloatingServer is the server API for Floating service.
// All implementations must embed UnimplementedFloatingServer
// for forward compatibility
type FloatingServer interface {
	Dimensions(context.Context, *DimensionsRequest) (*DimensionsResponse, error)
	mustEmbedUnimplementedFloatingServer()
}

// UnimplementedFloatingServer must be embedded to have forward compatible implementations.
type UnimplementedFloatingServer struct {
}

func (UnimplementedFloatingServer) Dimensions(context.Context, *DimensionsRequest) (*DimensionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dimensions not implemented")
}
func (UnimplementedFloatingServer) mustEmbedUnimplementedFloatingServer() {}

// UnsafeFloatingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FloatingServer will
// result in compilation errors.
type UnsafeFloatingServer interface {
	mustEmbedUnimplementedFloatingServer()
}

func RegisterFloatingServer(s grpc.ServiceRegistrar, srv FloatingServer) {
	s.RegisterService(&Floating_ServiceDesc, srv)
}

func _Floating_Dimensions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DimensionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FloatingServer).Dimensions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/browser.Floating/Dimensions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FloatingServer).Dimensions(ctx, req.(*DimensionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Floating_ServiceDesc is the grpc.ServiceDesc for Floating service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Floating_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "browser.Floating",
	HandlerType: (*FloatingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Dimensions",
			Handler:    _Floating_Dimensions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/browser.proto",
}
